[package]
name = "shipstern-example-jetstreamer"
version.workspace = true
description = "Example of using Jetstream source with Shipstern"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
anyhow = "1.0"
bs58 = { workspace = true }
clap = { workspace = true, features = ["derive", "cargo", "wrap_help"] }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
tracing = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
shipstern = { workspace = true }
shipstern-core = { workspace = true }
shipstern-jetstream-source = { workspace = true }
shipstern-spl-token-parser = { workspace = true }
