//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

pub(crate) mod r#close_position;
pub(crate) mod r#collect_fund_fee;
pub(crate) mod r#collect_protocol_fee;
pub(crate) mod r#collect_remaining_rewards;
pub(crate) mod r#create_amm_config;
pub(crate) mod r#create_operation_account;
pub(crate) mod r#create_permissionless_farm_switch;
pub(crate) mod r#create_pool;
pub(crate) mod r#create_support_mint_associated;
pub(crate) mod r#decrease_liquidity;
pub(crate) mod r#decrease_liquidity_v2;
pub(crate) mod r#increase_liquidity;
pub(crate) mod r#increase_liquidity_v2;
pub(crate) mod r#initialize_reward;
pub(crate) mod r#open_position;
pub(crate) mod r#open_position_v2;
pub(crate) mod r#open_position_with_token22_nft;
pub(crate) mod r#set_reward_params;
pub(crate) mod r#swap;
pub(crate) mod r#swap_router_base_in;
pub(crate) mod r#swap_v2;
pub(crate) mod r#toggle_permissionless_farm_switch;
pub(crate) mod r#transfer_reward_owner;
pub(crate) mod r#update_amm_config;
pub(crate) mod r#update_operation_account;
pub(crate) mod r#update_pool_status;
pub(crate) mod r#update_reward_infos;

pub use self::{
    r#close_position::*, r#collect_fund_fee::*, r#collect_protocol_fee::*,
    r#collect_remaining_rewards::*, r#create_amm_config::*, r#create_operation_account::*,
    r#create_permissionless_farm_switch::*, r#create_pool::*, r#create_support_mint_associated::*,
    r#decrease_liquidity::*, r#decrease_liquidity_v2::*, r#increase_liquidity::*,
    r#increase_liquidity_v2::*, r#initialize_reward::*, r#open_position::*, r#open_position_v2::*,
    r#open_position_with_token22_nft::*, r#set_reward_params::*, r#swap::*,
    r#swap_router_base_in::*, r#swap_v2::*, r#toggle_permissionless_farm_switch::*,
    r#transfer_reward_owner::*, r#update_amm_config::*, r#update_operation_account::*,
    r#update_pool_status::*, r#update_reward_infos::*,
};
