version: "3.9"

services:
  opentelemetry-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/opentelemetry-config.yaml", "${OTELCOL_ARGS}"]
    volumes:
      - ./opentelemetry-config.yaml:/etc/opentelemetry-config.yaml
    ports:
      - "4317:4317" # OTLP gRPC receiver
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus-config.yaml:/etc/prometheus/prometheus-config.yaml
    command: ["--config.file=/etc/prometheus/prometheus-config.yaml"]
    ports:
      - "9091:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  # demo:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: vixen_demo
  #   ports:
  #     - "3030:3030"
  #   environment:
  #     - RUST_LOG=info
  #   volumes:
  #     - ./Vixen.toml:/usr/local/bin/config/Vixen.toml
  #   command: ["./demo", "--config", "/usr/local/bin/config/Vixen.toml"]
