version: "3.9"

services:
  demo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vixen_demo
    environment:
      - RUST_LOG=info
    volumes:
      - ./Vixen.toml:/usr/local/bin/config/Vixen.toml
    command: ["./demo", "--config", "/usr/local/bin/config/Vixen.toml"]
