[package]
name = "shipstern-jetstream-source"
version.workspace = true
description = "Jetstream source for Shipstern"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme = "./../../README.md"

[dependencies]
async-trait = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "signal"] }
tracing = { workspace = true }
futures-util = { workspace = true, features = ["sink"] }
shipstern = { workspace = true }
shipstern-core = { workspace = true }
yellowstone-grpc-proto = { workspace = true }
yellowstone-grpc-client = { workspace = true }
serde = { workspace = true, features = ["derive"] }
clap = { workspace = true, features = ["derive", "cargo", "wrap_help"] }
thiserror = { workspace = true }
prost-types = { workspace = true }

jetstreamer-firehose = { workspace = true }
jetstreamer-utils = { workspace = true }
prometheus = { workspace = true, optional = true }

# Solana dependencies - upgraded to 4.2 with the main workspace
solana-transaction = { workspace = true }
solana-msg = { workspace = true }
solana-message = { workspace = true }
solana-instruction = { workspace = true }
solana-pubkey = { workspace = true }
solana-transaction-status = { workspace = true }
solana-runtime = { workspace = true }

bincode = "1.3"

[dev-dependencies]
toml = { workspace = true }
solana-reward-info = "6"
solana-hash = { workspace = true }

[features]
default = []
prometheus = ["dep:prometheus"]
