[package]
name = "shipstern-stake-pool-parser"
version.workspace = true
edition.workspace = true
description = "Shipstern program parser for SPL Stake Pool"
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
spl-pod = { workspace = true }
spl-stake-pool = { workspace = true, features = ["no-entrypoint"] }
shipstern-core = { workspace = true }
shipstern-proc-macro = { workspace = true }
shipstern-parser = { workspace = true }
shipstern-proto = { workspace = true, features = [
  "parser",
], optional = true }
thiserror.workspace = true
borsh.workspace = true
bs58.workspace = true
prost = { workspace = true, optional = true }
prost-types = { workspace = true, optional = true }

[dev-dependencies]
shipstern-mock = { workspace = true }
tokio.workspace = true

[features]
default = []
proto = [
  "dep:prost",
  "dep:prost-types",
  "shipstern-core/proto",
  "shipstern-proc-macro/proto",
]
