[package]
name = "shipstern-example-idl-parser"
description = "Example of generating parser from IDL"
publish = false
edition.workspace = true
license = "MIT"
repository = "https://github.com/rpcpool/shipstern"

[dependencies]
clap = { workspace = true, features = ["derive", "cargo", "wrap_help"] }
toml = { workspace = true }
tracing = { workspace = true }
rustls = { workspace = true }
borsh = { workspace = true, features = ["derive"] }
shipstern = { workspace = true }
shipstern-core = { workspace = true, features = ["proto"] }
shipstern-parser = { workspace = true }
shipstern-proc-macro = { workspace = true, features = ["proto"] }
shipstern-yellowstone-grpc-source = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
bs58 = { workspace = true }
serde = { workspace = true, optional = true }


[features]
default = []
serde = ["dep:serde"]
