//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

pub(crate) mod r#add_insurance_fund_stake;
pub(crate) mod r#add_perp_lp_shares;
pub(crate) mod r#admin_disable_update_perp_bid_ask_twap;
pub(crate) mod r#begin_swap;
pub(crate) mod r#cancel_order;
pub(crate) mod r#cancel_order_by_user_id;
pub(crate) mod r#cancel_orders;
pub(crate) mod r#cancel_orders_by_ids;
pub(crate) mod r#cancel_request_remove_insurance_fund_stake;
pub(crate) mod r#change_signed_msg_ws_delegate_status;
pub(crate) mod r#delete_initialized_perp_market;
pub(crate) mod r#delete_initialized_spot_market;
pub(crate) mod r#delete_prelaunch_oracle;
pub(crate) mod r#delete_signed_msg_user_orders;
pub(crate) mod r#delete_user;
pub(crate) mod r#deposit;
pub(crate) mod r#deposit_into_perp_market_fee_pool;
pub(crate) mod r#deposit_into_spot_market_revenue_pool;
pub(crate) mod r#deposit_into_spot_market_vault;
pub(crate) mod r#disable_user_high_leverage_mode;
pub(crate) mod r#enable_user_high_leverage_mode;
pub(crate) mod r#end_swap;
pub(crate) mod r#fill_perp_order;
pub(crate) mod r#fill_spot_order;
pub(crate) mod r#force_cancel_orders;
pub(crate) mod r#force_delete_user;
pub(crate) mod r#init_user_fuel;
pub(crate) mod r#initialize;
pub(crate) mod r#initialize_fuel_overflow;
pub(crate) mod r#initialize_high_leverage_mode_config;
pub(crate) mod r#initialize_insurance_fund_stake;
pub(crate) mod r#initialize_openbook_v2_fulfillment_config;
pub(crate) mod r#initialize_perp_market;
pub(crate) mod r#initialize_phoenix_fulfillment_config;
pub(crate) mod r#initialize_prediction_market;
pub(crate) mod r#initialize_prelaunch_oracle;
pub(crate) mod r#initialize_protected_maker_mode_config;
pub(crate) mod r#initialize_protocol_if_shares_transfer_config;
pub(crate) mod r#initialize_pyth_lazer_oracle;
pub(crate) mod r#initialize_pyth_pull_oracle;
pub(crate) mod r#initialize_referrer_name;
pub(crate) mod r#initialize_serum_fulfillment_config;
pub(crate) mod r#initialize_signed_msg_user_orders;
pub(crate) mod r#initialize_signed_msg_ws_delegates;
pub(crate) mod r#initialize_spot_market;
pub(crate) mod r#initialize_user;
pub(crate) mod r#initialize_user_stats;
pub(crate) mod r#liquidate_borrow_for_perp_pnl;
pub(crate) mod r#liquidate_perp;
pub(crate) mod r#liquidate_perp_pnl_for_deposit;
pub(crate) mod r#liquidate_perp_with_fill;
pub(crate) mod r#liquidate_spot;
pub(crate) mod r#liquidate_spot_with_swap_begin;
pub(crate) mod r#liquidate_spot_with_swap_end;
pub(crate) mod r#log_user_balances;
pub(crate) mod r#modify_order;
pub(crate) mod r#modify_order_by_user_id;
pub(crate) mod r#move_amm_price;
pub(crate) mod r#openbook_v2_fulfillment_config_status;
pub(crate) mod r#pause_spot_market_deposit_withdraw;
pub(crate) mod r#phoenix_fulfillment_config_status;
pub(crate) mod r#place_and_make_perp_order;
pub(crate) mod r#place_and_make_signed_msg_perp_order;
pub(crate) mod r#place_and_make_spot_order;
pub(crate) mod r#place_and_take_perp_order;
pub(crate) mod r#place_and_take_spot_order;
pub(crate) mod r#place_orders;
pub(crate) mod r#place_perp_order;
pub(crate) mod r#place_signed_msg_taker_order;
pub(crate) mod r#place_spot_order;
pub(crate) mod r#post_multi_pyth_pull_oracle_updates_atomic;
pub(crate) mod r#post_pyth_lazer_oracle_update;
pub(crate) mod r#post_pyth_pull_oracle_update_atomic;
pub(crate) mod r#recenter_perp_market_amm;
pub(crate) mod r#reclaim_rent;
pub(crate) mod r#remove_insurance_fund_stake;
pub(crate) mod r#remove_perp_lp_shares;
pub(crate) mod r#remove_perp_lp_shares_in_expiring_market;
pub(crate) mod r#repeg_amm_curve;
pub(crate) mod r#request_remove_insurance_fund_stake;
pub(crate) mod r#reset_fuel_season;
pub(crate) mod r#reset_perp_market_amm_oracle_twap;
pub(crate) mod r#resize_signed_msg_user_orders;
pub(crate) mod r#resolve_perp_bankruptcy;
pub(crate) mod r#resolve_perp_pnl_deficit;
pub(crate) mod r#resolve_spot_bankruptcy;
pub(crate) mod r#revert_fill;
pub(crate) mod r#set_user_status_to_being_liquidated;
pub(crate) mod r#settle_expired_market;
pub(crate) mod r#settle_expired_market_pools_to_revenue_pool;
pub(crate) mod r#settle_funding_payment;
pub(crate) mod r#settle_lp;
pub(crate) mod r#settle_multiple_pnls;
pub(crate) mod r#settle_pnl;
pub(crate) mod r#settle_revenue_to_insurance_fund;
pub(crate) mod r#sweep_fuel;
pub(crate) mod r#transfer_deposit;
pub(crate) mod r#transfer_perp_position;
pub(crate) mod r#transfer_pools;
pub(crate) mod r#transfer_protocol_if_shares;
pub(crate) mod r#trigger_order;
pub(crate) mod r#update_admin;
pub(crate) mod r#update_amm_jit_intensity;
pub(crate) mod r#update_amms;
pub(crate) mod r#update_discount_mint;
pub(crate) mod r#update_exchange_status;
pub(crate) mod r#update_funding_rate;
pub(crate) mod r#update_high_leverage_mode_config;
pub(crate) mod r#update_initial_pct_to_liquidate;
pub(crate) mod r#update_insurance_fund_unstaking_period;
pub(crate) mod r#update_k;
pub(crate) mod r#update_liquidation_duration;
pub(crate) mod r#update_liquidation_margin_buffer_ratio;
pub(crate) mod r#update_lp_cooldown_time;
pub(crate) mod r#update_oracle_guard_rails;
pub(crate) mod r#update_perp_auction_duration;
pub(crate) mod r#update_perp_bid_ask_twap;
pub(crate) mod r#update_perp_fee_structure;
pub(crate) mod r#update_perp_market_amm_oracle_twap;
pub(crate) mod r#update_perp_market_amm_summary_stats;
pub(crate) mod r#update_perp_market_base_spread;
pub(crate) mod r#update_perp_market_concentration_coef;
pub(crate) mod r#update_perp_market_contract_tier;
pub(crate) mod r#update_perp_market_curve_update_intensity;
pub(crate) mod r#update_perp_market_expiry;
pub(crate) mod r#update_perp_market_fee_adjustment;
pub(crate) mod r#update_perp_market_fuel;
pub(crate) mod r#update_perp_market_funding_period;
pub(crate) mod r#update_perp_market_high_leverage_margin_ratio;
pub(crate) mod r#update_perp_market_imf_factor;
pub(crate) mod r#update_perp_market_liquidation_fee;
pub(crate) mod r#update_perp_market_margin_ratio;
pub(crate) mod r#update_perp_market_max_fill_reserve_fraction;
pub(crate) mod r#update_perp_market_max_imbalances;
pub(crate) mod r#update_perp_market_max_open_interest;
pub(crate) mod r#update_perp_market_max_slippage_ratio;
pub(crate) mod r#update_perp_market_max_spread;
pub(crate) mod r#update_perp_market_min_order_size;
pub(crate) mod r#update_perp_market_name;
pub(crate) mod r#update_perp_market_number_of_users;
pub(crate) mod r#update_perp_market_oracle;
pub(crate) mod r#update_perp_market_paused_operations;
pub(crate) mod r#update_perp_market_per_lp_base;
pub(crate) mod r#update_perp_market_status;
pub(crate) mod r#update_perp_market_step_size_and_tick_size;
pub(crate) mod r#update_perp_market_target_base_asset_amount_per_lp;
pub(crate) mod r#update_perp_market_unrealized_asset_weight;
pub(crate) mod r#update_prelaunch_oracle;
pub(crate) mod r#update_prelaunch_oracle_params;
pub(crate) mod r#update_protected_maker_mode_config;
pub(crate) mod r#update_protocol_if_shares_transfer_config;
pub(crate) mod r#update_pyth_pull_oracle;
pub(crate) mod r#update_serum_fulfillment_config_status;
pub(crate) mod r#update_serum_vault;
pub(crate) mod r#update_spot_auction_duration;
pub(crate) mod r#update_spot_fee_structure;
pub(crate) mod r#update_spot_market_asset_tier;
pub(crate) mod r#update_spot_market_borrow_rate;
pub(crate) mod r#update_spot_market_cumulative_interest;
pub(crate) mod r#update_spot_market_expiry;
pub(crate) mod r#update_spot_market_fee_adjustment;
pub(crate) mod r#update_spot_market_fuel;
pub(crate) mod r#update_spot_market_if_factor;
pub(crate) mod r#update_spot_market_if_paused_operations;
pub(crate) mod r#update_spot_market_liquidation_fee;
pub(crate) mod r#update_spot_market_margin_weights;
pub(crate) mod r#update_spot_market_max_token_borrows;
pub(crate) mod r#update_spot_market_max_token_deposits;
pub(crate) mod r#update_spot_market_min_order_size;
pub(crate) mod r#update_spot_market_name;
pub(crate) mod r#update_spot_market_oracle;
pub(crate) mod r#update_spot_market_orders_enabled;
pub(crate) mod r#update_spot_market_paused_operations;
pub(crate) mod r#update_spot_market_pool_id;
pub(crate) mod r#update_spot_market_revenue_settle_period;
pub(crate) mod r#update_spot_market_scale_initial_asset_weight_start;
pub(crate) mod r#update_spot_market_status;
pub(crate) mod r#update_spot_market_step_size_and_tick_size;
pub(crate) mod r#update_state_max_initialize_user_fee;
pub(crate) mod r#update_state_max_number_of_sub_accounts;
pub(crate) mod r#update_state_settlement_duration;
pub(crate) mod r#update_user_advanced_lp;
pub(crate) mod r#update_user_custom_margin_ratio;
pub(crate) mod r#update_user_delegate;
pub(crate) mod r#update_user_fuel_bonus;
pub(crate) mod r#update_user_gov_token_insurance_stake;
pub(crate) mod r#update_user_gov_token_insurance_stake_devnet;
pub(crate) mod r#update_user_idle;
pub(crate) mod r#update_user_margin_trading_enabled;
pub(crate) mod r#update_user_name;
pub(crate) mod r#update_user_open_orders_count;
pub(crate) mod r#update_user_pool_id;
pub(crate) mod r#update_user_protected_maker_orders;
pub(crate) mod r#update_user_quote_asset_insurance_stake;
pub(crate) mod r#update_user_reduce_only;
pub(crate) mod r#update_user_stats_referrer_status;
pub(crate) mod r#update_whitelist_mint;
pub(crate) mod r#update_withdraw_guard_threshold;
pub(crate) mod r#withdraw;

pub use self::{
    r#add_insurance_fund_stake::*, r#add_perp_lp_shares::*,
    r#admin_disable_update_perp_bid_ask_twap::*, r#begin_swap::*, r#cancel_order::*,
    r#cancel_order_by_user_id::*, r#cancel_orders::*, r#cancel_orders_by_ids::*,
    r#cancel_request_remove_insurance_fund_stake::*, r#change_signed_msg_ws_delegate_status::*,
    r#delete_initialized_perp_market::*, r#delete_initialized_spot_market::*,
    r#delete_prelaunch_oracle::*, r#delete_signed_msg_user_orders::*, r#delete_user::*,
    r#deposit::*, r#deposit_into_perp_market_fee_pool::*,
    r#deposit_into_spot_market_revenue_pool::*, r#deposit_into_spot_market_vault::*,
    r#disable_user_high_leverage_mode::*, r#enable_user_high_leverage_mode::*, r#end_swap::*,
    r#fill_perp_order::*, r#fill_spot_order::*, r#force_cancel_orders::*, r#force_delete_user::*,
    r#init_user_fuel::*, r#initialize::*, r#initialize_fuel_overflow::*,
    r#initialize_high_leverage_mode_config::*, r#initialize_insurance_fund_stake::*,
    r#initialize_openbook_v2_fulfillment_config::*, r#initialize_perp_market::*,
    r#initialize_phoenix_fulfillment_config::*, r#initialize_prediction_market::*,
    r#initialize_prelaunch_oracle::*, r#initialize_protected_maker_mode_config::*,
    r#initialize_protocol_if_shares_transfer_config::*, r#initialize_pyth_lazer_oracle::*,
    r#initialize_pyth_pull_oracle::*, r#initialize_referrer_name::*,
    r#initialize_serum_fulfillment_config::*, r#initialize_signed_msg_user_orders::*,
    r#initialize_signed_msg_ws_delegates::*, r#initialize_spot_market::*, r#initialize_user::*,
    r#initialize_user_stats::*, r#liquidate_borrow_for_perp_pnl::*, r#liquidate_perp::*,
    r#liquidate_perp_pnl_for_deposit::*, r#liquidate_perp_with_fill::*, r#liquidate_spot::*,
    r#liquidate_spot_with_swap_begin::*, r#liquidate_spot_with_swap_end::*, r#log_user_balances::*,
    r#modify_order::*, r#modify_order_by_user_id::*, r#move_amm_price::*,
    r#openbook_v2_fulfillment_config_status::*, r#pause_spot_market_deposit_withdraw::*,
    r#phoenix_fulfillment_config_status::*, r#place_and_make_perp_order::*,
    r#place_and_make_signed_msg_perp_order::*, r#place_and_make_spot_order::*,
    r#place_and_take_perp_order::*, r#place_and_take_spot_order::*, r#place_orders::*,
    r#place_perp_order::*, r#place_signed_msg_taker_order::*, r#place_spot_order::*,
    r#post_multi_pyth_pull_oracle_updates_atomic::*, r#post_pyth_lazer_oracle_update::*,
    r#post_pyth_pull_oracle_update_atomic::*, r#recenter_perp_market_amm::*, r#reclaim_rent::*,
    r#remove_insurance_fund_stake::*, r#remove_perp_lp_shares::*,
    r#remove_perp_lp_shares_in_expiring_market::*, r#repeg_amm_curve::*,
    r#request_remove_insurance_fund_stake::*, r#reset_fuel_season::*,
    r#reset_perp_market_amm_oracle_twap::*, r#resize_signed_msg_user_orders::*,
    r#resolve_perp_bankruptcy::*, r#resolve_perp_pnl_deficit::*, r#resolve_spot_bankruptcy::*,
    r#revert_fill::*, r#set_user_status_to_being_liquidated::*, r#settle_expired_market::*,
    r#settle_expired_market_pools_to_revenue_pool::*, r#settle_funding_payment::*, r#settle_lp::*,
    r#settle_multiple_pnls::*, r#settle_pnl::*, r#settle_revenue_to_insurance_fund::*,
    r#sweep_fuel::*, r#transfer_deposit::*, r#transfer_perp_position::*, r#transfer_pools::*,
    r#transfer_protocol_if_shares::*, r#trigger_order::*, r#update_admin::*,
    r#update_amm_jit_intensity::*, r#update_amms::*, r#update_discount_mint::*,
    r#update_exchange_status::*, r#update_funding_rate::*, r#update_high_leverage_mode_config::*,
    r#update_initial_pct_to_liquidate::*, r#update_insurance_fund_unstaking_period::*,
    r#update_k::*, r#update_liquidation_duration::*, r#update_liquidation_margin_buffer_ratio::*,
    r#update_lp_cooldown_time::*, r#update_oracle_guard_rails::*,
    r#update_perp_auction_duration::*, r#update_perp_bid_ask_twap::*,
    r#update_perp_fee_structure::*, r#update_perp_market_amm_oracle_twap::*,
    r#update_perp_market_amm_summary_stats::*, r#update_perp_market_base_spread::*,
    r#update_perp_market_concentration_coef::*, r#update_perp_market_contract_tier::*,
    r#update_perp_market_curve_update_intensity::*, r#update_perp_market_expiry::*,
    r#update_perp_market_fee_adjustment::*, r#update_perp_market_fuel::*,
    r#update_perp_market_funding_period::*, r#update_perp_market_high_leverage_margin_ratio::*,
    r#update_perp_market_imf_factor::*, r#update_perp_market_liquidation_fee::*,
    r#update_perp_market_margin_ratio::*, r#update_perp_market_max_fill_reserve_fraction::*,
    r#update_perp_market_max_imbalances::*, r#update_perp_market_max_open_interest::*,
    r#update_perp_market_max_slippage_ratio::*, r#update_perp_market_max_spread::*,
    r#update_perp_market_min_order_size::*, r#update_perp_market_name::*,
    r#update_perp_market_number_of_users::*, r#update_perp_market_oracle::*,
    r#update_perp_market_paused_operations::*, r#update_perp_market_per_lp_base::*,
    r#update_perp_market_status::*, r#update_perp_market_step_size_and_tick_size::*,
    r#update_perp_market_target_base_asset_amount_per_lp::*,
    r#update_perp_market_unrealized_asset_weight::*, r#update_prelaunch_oracle::*,
    r#update_prelaunch_oracle_params::*, r#update_protected_maker_mode_config::*,
    r#update_protocol_if_shares_transfer_config::*, r#update_pyth_pull_oracle::*,
    r#update_serum_fulfillment_config_status::*, r#update_serum_vault::*,
    r#update_spot_auction_duration::*, r#update_spot_fee_structure::*,
    r#update_spot_market_asset_tier::*, r#update_spot_market_borrow_rate::*,
    r#update_spot_market_cumulative_interest::*, r#update_spot_market_expiry::*,
    r#update_spot_market_fee_adjustment::*, r#update_spot_market_fuel::*,
    r#update_spot_market_if_factor::*, r#update_spot_market_if_paused_operations::*,
    r#update_spot_market_liquidation_fee::*, r#update_spot_market_margin_weights::*,
    r#update_spot_market_max_token_borrows::*, r#update_spot_market_max_token_deposits::*,
    r#update_spot_market_min_order_size::*, r#update_spot_market_name::*,
    r#update_spot_market_oracle::*, r#update_spot_market_orders_enabled::*,
    r#update_spot_market_paused_operations::*, r#update_spot_market_pool_id::*,
    r#update_spot_market_revenue_settle_period::*,
    r#update_spot_market_scale_initial_asset_weight_start::*, r#update_spot_market_status::*,
    r#update_spot_market_step_size_and_tick_size::*, r#update_state_max_initialize_user_fee::*,
    r#update_state_max_number_of_sub_accounts::*, r#update_state_settlement_duration::*,
    r#update_user_advanced_lp::*, r#update_user_custom_margin_ratio::*, r#update_user_delegate::*,
    r#update_user_fuel_bonus::*, r#update_user_gov_token_insurance_stake::*,
    r#update_user_gov_token_insurance_stake_devnet::*, r#update_user_idle::*,
    r#update_user_margin_trading_enabled::*, r#update_user_name::*,
    r#update_user_open_orders_count::*, r#update_user_pool_id::*,
    r#update_user_protected_maker_orders::*, r#update_user_quote_asset_insurance_stake::*,
    r#update_user_reduce_only::*, r#update_user_stats_referrer_status::*,
    r#update_whitelist_mint::*, r#update_withdraw_guard_threshold::*, r#withdraw::*,
};
