//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::{BorshDeserialize, BorshSerialize};

use crate::generated::types::SpotFulfillmentConfigStatus;

/// Accounts.
#[derive(Debug)]
pub struct PhoenixFulfillmentConfigStatus {
    pub state: solana_program::pubkey::Pubkey,

    pub phoenix_fulfillment_config: solana_program::pubkey::Pubkey,

    pub admin: solana_program::pubkey::Pubkey,
}

impl PhoenixFulfillmentConfigStatus {
    pub fn instruction(
        &self,
        args: PhoenixFulfillmentConfigStatusInstructionArgs,
    ) -> solana_program::instruction::Instruction {
        self.instruction_with_remaining_accounts(args, &[])
    }

    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::vec_init_then_push)]
    pub fn instruction_with_remaining_accounts(
        &self,
        args: PhoenixFulfillmentConfigStatusInstructionArgs,
        remaining_accounts: &[solana_program::instruction::AccountMeta],
    ) -> solana_program::instruction::Instruction {
        let mut accounts = Vec::with_capacity(3 + remaining_accounts.len());
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.state, false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new(
            self.phoenix_fulfillment_config,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new(
            self.admin, true,
        ));
        accounts.extend_from_slice(remaining_accounts);
        let mut data =
            borsh::to_vec(&PhoenixFulfillmentConfigStatusInstructionData::new()).unwrap();
        let mut args = borsh::to_vec(&args).unwrap();
        data.append(&mut args);

        solana_program::instruction::Instruction {
            program_id: crate::DRIFT_ID,
            accounts,
            data,
        }
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct PhoenixFulfillmentConfigStatusInstructionData {
    discriminator: [u8; 8],
}

impl PhoenixFulfillmentConfigStatusInstructionData {
    pub fn new() -> Self {
        Self {
            discriminator: [96, 31, 113, 32, 12, 203, 7, 154],
        }
    }
}

impl Default for PhoenixFulfillmentConfigStatusInstructionData {
    fn default() -> Self { Self::new() }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct PhoenixFulfillmentConfigStatusInstructionArgs {
    pub status: SpotFulfillmentConfigStatus,
}

/// Instruction builder for `PhoenixFulfillmentConfigStatus`.
///
/// ### Accounts:
///
///   0. `[]` state
///   1. `[writable]` phoenix_fulfillment_config
///   2. `[writable, signer]` admin
#[derive(Clone, Debug, Default)]
pub struct PhoenixFulfillmentConfigStatusBuilder {
    state: Option<solana_program::pubkey::Pubkey>,
    phoenix_fulfillment_config: Option<solana_program::pubkey::Pubkey>,
    admin: Option<solana_program::pubkey::Pubkey>,
    status: Option<SpotFulfillmentConfigStatus>,
    __remaining_accounts: Vec<solana_program::instruction::AccountMeta>,
}

impl PhoenixFulfillmentConfigStatusBuilder {
    pub fn new() -> Self { Self::default() }

    #[inline(always)]
    pub fn state(&mut self, state: solana_program::pubkey::Pubkey) -> &mut Self {
        self.state = Some(state);
        self
    }

    #[inline(always)]
    pub fn phoenix_fulfillment_config(
        &mut self,
        phoenix_fulfillment_config: solana_program::pubkey::Pubkey,
    ) -> &mut Self {
        self.phoenix_fulfillment_config = Some(phoenix_fulfillment_config);
        self
    }

    #[inline(always)]
    pub fn admin(&mut self, admin: solana_program::pubkey::Pubkey) -> &mut Self {
        self.admin = Some(admin);
        self
    }

    #[inline(always)]
    pub fn status(&mut self, status: SpotFulfillmentConfigStatus) -> &mut Self {
        self.status = Some(status);
        self
    }

    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: solana_program::instruction::AccountMeta,
    ) -> &mut Self {
        self.__remaining_accounts.push(account);
        self
    }

    /// Add additional accounts to the instruction.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[solana_program::instruction::AccountMeta],
    ) -> &mut Self {
        self.__remaining_accounts.extend_from_slice(accounts);
        self
    }

    #[allow(clippy::clone_on_copy)]
    pub fn instruction(&self) -> solana_program::instruction::Instruction {
        let accounts = PhoenixFulfillmentConfigStatus {
            state: self.state.expect("state is not set"),
            phoenix_fulfillment_config: self
                .phoenix_fulfillment_config
                .expect("phoenix_fulfillment_config is not set"),
            admin: self.admin.expect("admin is not set"),
        };
        let args = PhoenixFulfillmentConfigStatusInstructionArgs {
            status: self.status.clone().expect("status is not set"),
        };

        accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
    }
}

/// `phoenix_fulfillment_config_status` CPI accounts.
pub struct PhoenixFulfillmentConfigStatusCpiAccounts<'a, 'b> {
    pub state: &'b solana_program::account_info::AccountInfo<'a>,

    pub phoenix_fulfillment_config: &'b solana_program::account_info::AccountInfo<'a>,

    pub admin: &'b solana_program::account_info::AccountInfo<'a>,
}

/// `phoenix_fulfillment_config_status` CPI instruction.
pub struct PhoenixFulfillmentConfigStatusCpi<'a, 'b> {
    /// The program to invoke.
    pub __program: &'b solana_program::account_info::AccountInfo<'a>,

    pub state: &'b solana_program::account_info::AccountInfo<'a>,

    pub phoenix_fulfillment_config: &'b solana_program::account_info::AccountInfo<'a>,

    pub admin: &'b solana_program::account_info::AccountInfo<'a>,
    /// The arguments for the instruction.
    pub __args: PhoenixFulfillmentConfigStatusInstructionArgs,
}

impl<'a, 'b> PhoenixFulfillmentConfigStatusCpi<'a, 'b> {
    pub fn new(
        program: &'b solana_program::account_info::AccountInfo<'a>,
        accounts: PhoenixFulfillmentConfigStatusCpiAccounts<'a, 'b>,
        args: PhoenixFulfillmentConfigStatusInstructionArgs,
    ) -> Self {
        Self {
            __program: program,
            state: accounts.state,
            phoenix_fulfillment_config: accounts.phoenix_fulfillment_config,
            admin: accounts.admin,
            __args: args,
        }
    }

    #[inline(always)]
    pub fn invoke(&self) -> solana_program::entrypoint::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], &[])
    }

    #[inline(always)]
    pub fn invoke_with_remaining_accounts(
        &self,
        remaining_accounts: &[(
            &'b solana_program::account_info::AccountInfo<'a>,
            bool,
            bool,
        )],
    ) -> solana_program::entrypoint::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
    }

    #[inline(always)]
    pub fn invoke_signed(
        &self,
        signers_seeds: &[&[&[u8]]],
    ) -> solana_program::entrypoint::ProgramResult {
        self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
    }

    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed_with_remaining_accounts(
        &self,
        signers_seeds: &[&[&[u8]]],
        remaining_accounts: &[(
            &'b solana_program::account_info::AccountInfo<'a>,
            bool,
            bool,
        )],
    ) -> solana_program::entrypoint::ProgramResult {
        let mut accounts = Vec::with_capacity(3 + remaining_accounts.len());
        accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.state.key,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new(
            *self.phoenix_fulfillment_config.key,
            false,
        ));
        accounts.push(solana_program::instruction::AccountMeta::new(
            *self.admin.key,
            true,
        ));
        remaining_accounts.iter().for_each(|remaining_account| {
            accounts.push(solana_program::instruction::AccountMeta {
                pubkey: *remaining_account.0.key,
                is_signer: remaining_account.1,
                is_writable: remaining_account.2,
            })
        });
        let mut data =
            borsh::to_vec(&PhoenixFulfillmentConfigStatusInstructionData::new()).unwrap();
        let mut args = borsh::to_vec(&self.__args).unwrap();
        data.append(&mut args);

        let instruction = solana_program::instruction::Instruction {
            program_id: crate::DRIFT_ID,
            accounts,
            data,
        };
        let mut account_infos = Vec::with_capacity(4 + remaining_accounts.len());
        account_infos.push(self.__program.clone());
        account_infos.push(self.state.clone());
        account_infos.push(self.phoenix_fulfillment_config.clone());
        account_infos.push(self.admin.clone());
        remaining_accounts
            .iter()
            .for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

        if signers_seeds.is_empty() {
            solana_program::program::invoke(&instruction, &account_infos)
        } else {
            solana_program::program::invoke_signed(&instruction, &account_infos, signers_seeds)
        }
    }
}

/// Instruction builder for `PhoenixFulfillmentConfigStatus` via CPI.
///
/// ### Accounts:
///
///   0. `[]` state
///   1. `[writable]` phoenix_fulfillment_config
///   2. `[writable, signer]` admin
#[derive(Clone, Debug)]
pub struct PhoenixFulfillmentConfigStatusCpiBuilder<'a, 'b> {
    instruction: Box<PhoenixFulfillmentConfigStatusCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> PhoenixFulfillmentConfigStatusCpiBuilder<'a, 'b> {
    pub fn new(program: &'b solana_program::account_info::AccountInfo<'a>) -> Self {
        let instruction = Box::new(PhoenixFulfillmentConfigStatusCpiBuilderInstruction {
            __program: program,
            state: None,
            phoenix_fulfillment_config: None,
            admin: None,
            status: None,
            __remaining_accounts: Vec::new(),
        });
        Self { instruction }
    }

    #[inline(always)]
    pub fn state(&mut self, state: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.state = Some(state);
        self
    }

    #[inline(always)]
    pub fn phoenix_fulfillment_config(
        &mut self,
        phoenix_fulfillment_config: &'b solana_program::account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.phoenix_fulfillment_config = Some(phoenix_fulfillment_config);
        self
    }

    #[inline(always)]
    pub fn admin(&mut self, admin: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.admin = Some(admin);
        self
    }

    #[inline(always)]
    pub fn status(&mut self, status: SpotFulfillmentConfigStatus) -> &mut Self {
        self.instruction.status = Some(status);
        self
    }

    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: &'b solana_program::account_info::AccountInfo<'a>,
        is_writable: bool,
        is_signer: bool,
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .push((account, is_writable, is_signer));
        self
    }

    /// Add additional accounts to the instruction.
    ///
    /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
    /// and a `bool` indicating whether the account is a signer or not.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[(
            &'b solana_program::account_info::AccountInfo<'a>,
            bool,
            bool,
        )],
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .extend_from_slice(accounts);
        self
    }

    #[inline(always)]
    pub fn invoke(&self) -> solana_program::entrypoint::ProgramResult { self.invoke_signed(&[]) }

    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed(
        &self,
        signers_seeds: &[&[&[u8]]],
    ) -> solana_program::entrypoint::ProgramResult {
        let args = PhoenixFulfillmentConfigStatusInstructionArgs {
            status: self.instruction.status.clone().expect("status is not set"),
        };
        let instruction = PhoenixFulfillmentConfigStatusCpi {
            __program: self.instruction.__program,

            state: self.instruction.state.expect("state is not set"),

            phoenix_fulfillment_config: self
                .instruction
                .phoenix_fulfillment_config
                .expect("phoenix_fulfillment_config is not set"),

            admin: self.instruction.admin.expect("admin is not set"),
            __args: args,
        };
        instruction.invoke_signed_with_remaining_accounts(
            signers_seeds,
            &self.instruction.__remaining_accounts,
        )
    }
}

#[derive(Clone, Debug)]
struct PhoenixFulfillmentConfigStatusCpiBuilderInstruction<'a, 'b> {
    __program: &'b solana_program::account_info::AccountInfo<'a>,
    state: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    phoenix_fulfillment_config: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    admin: Option<&'b solana_program::account_info::AccountInfo<'a>>,
    status: Option<SpotFulfillmentConfigStatus>,
    /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
    __remaining_accounts: Vec<(
        &'b solana_program::account_info::AccountInfo<'a>,
        bool,
        bool,
    )>,
}
