//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshSerialize;
use borsh::BorshDeserialize;

/// Accounts.
#[derive(Debug)]
pub struct DepositObligationCollateralV2 {
      
              
          pub owner: solana_program::pubkey::Pubkey,
          
              
          pub obligation: solana_program::pubkey::Pubkey,
          
              
          pub lending_market: solana_program::pubkey::Pubkey,
          
              
          pub deposit_reserve: solana_program::pubkey::Pubkey,
          
              
          pub reserve_destination_collateral: solana_program::pubkey::Pubkey,
          
              
          pub user_source_collateral: solana_program::pubkey::Pubkey,
          
              
          pub token_program: solana_program::pubkey::Pubkey,
          
              
          pub instruction_sysvar_account: solana_program::pubkey::Pubkey,
          
              
          pub lending_market_authority: solana_program::pubkey::Pubkey,
          
              
          pub obligation_farm_user_state: Option<solana_program::pubkey::Pubkey>,
          
              
          pub reserve_farm_state: Option<solana_program::pubkey::Pubkey>,
          
              
          pub farms_program: solana_program::pubkey::Pubkey,
      }

impl DepositObligationCollateralV2 {
  pub fn instruction(&self, args: DepositObligationCollateralV2InstructionArgs) -> solana_program::instruction::Instruction {
    self.instruction_with_remaining_accounts(args, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::vec_init_then_push)]
  pub fn instruction_with_remaining_accounts(&self, args: DepositObligationCollateralV2InstructionArgs, remaining_accounts: &[solana_program::instruction::AccountMeta]) -> solana_program::instruction::Instruction {
    let mut accounts = Vec::with_capacity(12+ remaining_accounts.len());
                            accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.owner,
            true
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new(
            self.obligation,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.lending_market,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new(
            self.deposit_reserve,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new(
            self.reserve_destination_collateral,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new(
            self.user_source_collateral,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.token_program,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.instruction_sysvar_account,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.lending_market_authority,
            false
          ));
                                                      if let Some(obligation_farm_user_state) = self.obligation_farm_user_state {
              accounts.push(solana_program::instruction::AccountMeta::new(
                obligation_farm_user_state,
                false,
              ));
            } else {
              accounts.push(solana_program::instruction::AccountMeta::new_readonly(
                crate::KAMINO_LENDING_ID,
                false,
              ));
            }
                                                                if let Some(reserve_farm_state) = self.reserve_farm_state {
              accounts.push(solana_program::instruction::AccountMeta::new(
                reserve_farm_state,
                false,
              ));
            } else {
              accounts.push(solana_program::instruction::AccountMeta::new_readonly(
                crate::KAMINO_LENDING_ID,
                false,
              ));
            }
                                                    accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            self.farms_program,
            false
          ));
                      accounts.extend_from_slice(remaining_accounts);
    let mut data = borsh::to_vec(&DepositObligationCollateralV2InstructionData::new()).unwrap();
          let mut args = borsh::to_vec(&args).unwrap();
      data.append(&mut args);
    
    solana_program::instruction::Instruction {
      program_id: crate::KAMINO_LENDING_ID,
      accounts,
      data,
    }
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
 pub struct DepositObligationCollateralV2InstructionData {
            discriminator: [u8; 8],
            }

impl DepositObligationCollateralV2InstructionData {
  pub fn new() -> Self {
    Self {
                        discriminator: [137, 145, 151, 94, 167, 113, 4, 145],
                                }
  }
}

impl Default for DepositObligationCollateralV2InstructionData {
  fn default() -> Self {
    Self::new()
  }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
 pub struct DepositObligationCollateralV2InstructionArgs {
                  pub collateral_amount: u64,
      }


/// Instruction builder for `DepositObligationCollateralV2`.
///
/// ### Accounts:
///
                ///   0. `[signer]` owner
                ///   1. `[writable]` obligation
          ///   2. `[]` lending_market
                ///   3. `[writable]` deposit_reserve
                ///   4. `[writable]` reserve_destination_collateral
                ///   5. `[writable]` user_source_collateral
                ///   6. `[optional]` token_program (default to `TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA`)
                ///   7. `[optional]` instruction_sysvar_account (default to `Sysvar1nstructions1111111111111111111111111`)
          ///   8. `[]` lending_market_authority
                      ///   9. `[writable, optional]` obligation_farm_user_state
                      ///   10. `[writable, optional]` reserve_farm_state
          ///   11. `[]` farms_program
#[derive(Clone, Debug, Default)]
pub struct DepositObligationCollateralV2Builder {
            owner: Option<solana_program::pubkey::Pubkey>,
                obligation: Option<solana_program::pubkey::Pubkey>,
                lending_market: Option<solana_program::pubkey::Pubkey>,
                deposit_reserve: Option<solana_program::pubkey::Pubkey>,
                reserve_destination_collateral: Option<solana_program::pubkey::Pubkey>,
                user_source_collateral: Option<solana_program::pubkey::Pubkey>,
                token_program: Option<solana_program::pubkey::Pubkey>,
                instruction_sysvar_account: Option<solana_program::pubkey::Pubkey>,
                lending_market_authority: Option<solana_program::pubkey::Pubkey>,
                obligation_farm_user_state: Option<solana_program::pubkey::Pubkey>,
                reserve_farm_state: Option<solana_program::pubkey::Pubkey>,
                farms_program: Option<solana_program::pubkey::Pubkey>,
                        collateral_amount: Option<u64>,
        __remaining_accounts: Vec<solana_program::instruction::AccountMeta>,
}

impl DepositObligationCollateralV2Builder {
  pub fn new() -> Self {
    Self::default()
  }
            #[inline(always)]
    pub fn owner(&mut self, owner: solana_program::pubkey::Pubkey) -> &mut Self {
                        self.owner = Some(owner);
                    self
    }
            #[inline(always)]
    pub fn obligation(&mut self, obligation: solana_program::pubkey::Pubkey) -> &mut Self {
                        self.obligation = Some(obligation);
                    self
    }
            #[inline(always)]
    pub fn lending_market(&mut self, lending_market: solana_program::pubkey::Pubkey) -> &mut Self {
                        self.lending_market = Some(lending_market);
                    self
    }
            #[inline(always)]
    pub fn deposit_reserve(&mut self, deposit_reserve: solana_program::pubkey::Pubkey) -> &mut Self {
                        self.deposit_reserve = Some(deposit_reserve);
                    self
    }
            #[inline(always)]
    pub fn reserve_destination_collateral(&mut self, reserve_destination_collateral: solana_program::pubkey::Pubkey) -> &mut Self {
                        self.reserve_destination_collateral = Some(reserve_destination_collateral);
                    self
    }
            #[inline(always)]
    pub fn user_source_collateral(&mut self, user_source_collateral: solana_program::pubkey::Pubkey) -> &mut Self {
                        self.user_source_collateral = Some(user_source_collateral);
                    self
    }
            /// `[optional account, default to 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA']`
#[inline(always)]
    pub fn token_program(&mut self, token_program: solana_program::pubkey::Pubkey) -> &mut Self {
                        self.token_program = Some(token_program);
                    self
    }
            /// `[optional account, default to 'Sysvar1nstructions1111111111111111111111111']`
#[inline(always)]
    pub fn instruction_sysvar_account(&mut self, instruction_sysvar_account: solana_program::pubkey::Pubkey) -> &mut Self {
                        self.instruction_sysvar_account = Some(instruction_sysvar_account);
                    self
    }
            #[inline(always)]
    pub fn lending_market_authority(&mut self, lending_market_authority: solana_program::pubkey::Pubkey) -> &mut Self {
                        self.lending_market_authority = Some(lending_market_authority);
                    self
    }
            /// `[optional account]`
#[inline(always)]
    pub fn obligation_farm_user_state(&mut self, obligation_farm_user_state: Option<solana_program::pubkey::Pubkey>) -> &mut Self {
                        self.obligation_farm_user_state = obligation_farm_user_state;
                    self
    }
            /// `[optional account]`
#[inline(always)]
    pub fn reserve_farm_state(&mut self, reserve_farm_state: Option<solana_program::pubkey::Pubkey>) -> &mut Self {
                        self.reserve_farm_state = reserve_farm_state;
                    self
    }
            #[inline(always)]
    pub fn farms_program(&mut self, farms_program: solana_program::pubkey::Pubkey) -> &mut Self {
                        self.farms_program = Some(farms_program);
                    self
    }
                    #[inline(always)]
      pub fn collateral_amount(&mut self, collateral_amount: u64) -> &mut Self {
        self.collateral_amount = Some(collateral_amount);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: solana_program::instruction::AccountMeta) -> &mut Self {
    self.__remaining_accounts.push(account);
    self
  }
  /// Add additional accounts to the instruction.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[solana_program::instruction::AccountMeta]) -> &mut Self {
    self.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[allow(clippy::clone_on_copy)]
  pub fn instruction(&self) -> solana_program::instruction::Instruction {
    let accounts = DepositObligationCollateralV2 {
                              owner: self.owner.expect("owner is not set"),
                                        obligation: self.obligation.expect("obligation is not set"),
                                        lending_market: self.lending_market.expect("lending_market is not set"),
                                        deposit_reserve: self.deposit_reserve.expect("deposit_reserve is not set"),
                                        reserve_destination_collateral: self.reserve_destination_collateral.expect("reserve_destination_collateral is not set"),
                                        user_source_collateral: self.user_source_collateral.expect("user_source_collateral is not set"),
                                        token_program: self.token_program.unwrap_or(solana_program::pubkey!("TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA")),
                                        instruction_sysvar_account: self.instruction_sysvar_account.unwrap_or(solana_program::pubkey!("Sysvar1nstructions1111111111111111111111111")),
                                        lending_market_authority: self.lending_market_authority.expect("lending_market_authority is not set"),
                                        obligation_farm_user_state: self.obligation_farm_user_state,
                                        reserve_farm_state: self.reserve_farm_state,
                                        farms_program: self.farms_program.expect("farms_program is not set"),
                      };
          let args = DepositObligationCollateralV2InstructionArgs {
                                                              collateral_amount: self.collateral_amount.clone().expect("collateral_amount is not set"),
                                    };
    
    accounts.instruction_with_remaining_accounts(args, &self.__remaining_accounts)
  }
}

  /// `deposit_obligation_collateral_v2` CPI accounts.
  pub struct DepositObligationCollateralV2CpiAccounts<'a, 'b> {
          
                    
              pub owner: &'b solana_program::account_info::AccountInfo<'a>,
                
                    
              pub obligation: &'b solana_program::account_info::AccountInfo<'a>,
                
                    
              pub lending_market: &'b solana_program::account_info::AccountInfo<'a>,
                
                    
              pub deposit_reserve: &'b solana_program::account_info::AccountInfo<'a>,
                
                    
              pub reserve_destination_collateral: &'b solana_program::account_info::AccountInfo<'a>,
                
                    
              pub user_source_collateral: &'b solana_program::account_info::AccountInfo<'a>,
                
                    
              pub token_program: &'b solana_program::account_info::AccountInfo<'a>,
                
                    
              pub instruction_sysvar_account: &'b solana_program::account_info::AccountInfo<'a>,
                
                    
              pub lending_market_authority: &'b solana_program::account_info::AccountInfo<'a>,
                
                    
              pub obligation_farm_user_state: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                
                    
              pub reserve_farm_state: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                
                    
              pub farms_program: &'b solana_program::account_info::AccountInfo<'a>,
            }

/// `deposit_obligation_collateral_v2` CPI instruction.
pub struct DepositObligationCollateralV2Cpi<'a, 'b> {
  /// The program to invoke.
  pub __program: &'b solana_program::account_info::AccountInfo<'a>,
      
              
          pub owner: &'b solana_program::account_info::AccountInfo<'a>,
          
              
          pub obligation: &'b solana_program::account_info::AccountInfo<'a>,
          
              
          pub lending_market: &'b solana_program::account_info::AccountInfo<'a>,
          
              
          pub deposit_reserve: &'b solana_program::account_info::AccountInfo<'a>,
          
              
          pub reserve_destination_collateral: &'b solana_program::account_info::AccountInfo<'a>,
          
              
          pub user_source_collateral: &'b solana_program::account_info::AccountInfo<'a>,
          
              
          pub token_program: &'b solana_program::account_info::AccountInfo<'a>,
          
              
          pub instruction_sysvar_account: &'b solana_program::account_info::AccountInfo<'a>,
          
              
          pub lending_market_authority: &'b solana_program::account_info::AccountInfo<'a>,
          
              
          pub obligation_farm_user_state: Option<&'b solana_program::account_info::AccountInfo<'a>>,
          
              
          pub reserve_farm_state: Option<&'b solana_program::account_info::AccountInfo<'a>>,
          
              
          pub farms_program: &'b solana_program::account_info::AccountInfo<'a>,
            /// The arguments for the instruction.
    pub __args: DepositObligationCollateralV2InstructionArgs,
  }

impl<'a, 'b> DepositObligationCollateralV2Cpi<'a, 'b> {
  pub fn new(
    program: &'b solana_program::account_info::AccountInfo<'a>,
          accounts: DepositObligationCollateralV2CpiAccounts<'a, 'b>,
              args: DepositObligationCollateralV2InstructionArgs,
      ) -> Self {
    Self {
      __program: program,
              owner: accounts.owner,
              obligation: accounts.obligation,
              lending_market: accounts.lending_market,
              deposit_reserve: accounts.deposit_reserve,
              reserve_destination_collateral: accounts.reserve_destination_collateral,
              user_source_collateral: accounts.user_source_collateral,
              token_program: accounts.token_program,
              instruction_sysvar_account: accounts.instruction_sysvar_account,
              lending_market_authority: accounts.lending_market_authority,
              obligation_farm_user_state: accounts.obligation_farm_user_state,
              reserve_farm_state: accounts.reserve_farm_state,
              farms_program: accounts.farms_program,
                    __args: args,
          }
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program::entrypoint::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], &[])
  }
  #[inline(always)]
  pub fn invoke_with_remaining_accounts(&self, remaining_accounts: &[(&'b solana_program::account_info::AccountInfo<'a>, bool, bool)]) -> solana_program::entrypoint::ProgramResult {
    self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
  }
  #[inline(always)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program::entrypoint::ProgramResult {
    self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
  }
  #[allow(clippy::arithmetic_side_effects)]
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed_with_remaining_accounts(
    &self,
    signers_seeds: &[&[&[u8]]],
    remaining_accounts: &[(&'b solana_program::account_info::AccountInfo<'a>, bool, bool)]
  ) -> solana_program::entrypoint::ProgramResult {
    let mut accounts = Vec::with_capacity(12+ remaining_accounts.len());
                            accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.owner.key,
            true
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new(
            *self.obligation.key,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.lending_market.key,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new(
            *self.deposit_reserve.key,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new(
            *self.reserve_destination_collateral.key,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new(
            *self.user_source_collateral.key,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.token_program.key,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.instruction_sysvar_account.key,
            false
          ));
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.lending_market_authority.key,
            false
          ));
                                          if let Some(obligation_farm_user_state) = self.obligation_farm_user_state {
            accounts.push(solana_program::instruction::AccountMeta::new(
              *obligation_farm_user_state.key,
              false,
            ));
          } else {
            accounts.push(solana_program::instruction::AccountMeta::new_readonly(
              crate::KAMINO_LENDING_ID,
              false,
            ));
          }
                                          if let Some(reserve_farm_state) = self.reserve_farm_state {
            accounts.push(solana_program::instruction::AccountMeta::new(
              *reserve_farm_state.key,
              false,
            ));
          } else {
            accounts.push(solana_program::instruction::AccountMeta::new_readonly(
              crate::KAMINO_LENDING_ID,
              false,
            ));
          }
                                          accounts.push(solana_program::instruction::AccountMeta::new_readonly(
            *self.farms_program.key,
            false
          ));
                      remaining_accounts.iter().for_each(|remaining_account| {
      accounts.push(solana_program::instruction::AccountMeta {
          pubkey: *remaining_account.0.key,
          is_signer: remaining_account.1,
          is_writable: remaining_account.2,
      })
    });
    let mut data = borsh::to_vec(&DepositObligationCollateralV2InstructionData::new()).unwrap();
          let mut args = borsh::to_vec(&self.__args).unwrap();
      data.append(&mut args);
    
    let instruction = solana_program::instruction::Instruction {
      program_id: crate::KAMINO_LENDING_ID,
      accounts,
      data,
    };
    let mut account_infos = Vec::with_capacity(13 + remaining_accounts.len());
    account_infos.push(self.__program.clone());
                  account_infos.push(self.owner.clone());
                        account_infos.push(self.obligation.clone());
                        account_infos.push(self.lending_market.clone());
                        account_infos.push(self.deposit_reserve.clone());
                        account_infos.push(self.reserve_destination_collateral.clone());
                        account_infos.push(self.user_source_collateral.clone());
                        account_infos.push(self.token_program.clone());
                        account_infos.push(self.instruction_sysvar_account.clone());
                        account_infos.push(self.lending_market_authority.clone());
                        if let Some(obligation_farm_user_state) = self.obligation_farm_user_state {
          account_infos.push(obligation_farm_user_state.clone());
        }
                        if let Some(reserve_farm_state) = self.reserve_farm_state {
          account_infos.push(reserve_farm_state.clone());
        }
                        account_infos.push(self.farms_program.clone());
              remaining_accounts.iter().for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

    if signers_seeds.is_empty() {
      solana_program::program::invoke(&instruction, &account_infos)
    } else {
      solana_program::program::invoke_signed(&instruction, &account_infos, signers_seeds)
    }
  }
}

/// Instruction builder for `DepositObligationCollateralV2` via CPI.
///
/// ### Accounts:
///
                ///   0. `[signer]` owner
                ///   1. `[writable]` obligation
          ///   2. `[]` lending_market
                ///   3. `[writable]` deposit_reserve
                ///   4. `[writable]` reserve_destination_collateral
                ///   5. `[writable]` user_source_collateral
          ///   6. `[]` token_program
          ///   7. `[]` instruction_sysvar_account
          ///   8. `[]` lending_market_authority
                      ///   9. `[writable, optional]` obligation_farm_user_state
                      ///   10. `[writable, optional]` reserve_farm_state
          ///   11. `[]` farms_program
#[derive(Clone, Debug)]
pub struct DepositObligationCollateralV2CpiBuilder<'a, 'b> {
  instruction: Box<DepositObligationCollateralV2CpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> DepositObligationCollateralV2CpiBuilder<'a, 'b> {
  pub fn new(program: &'b solana_program::account_info::AccountInfo<'a>) -> Self {
    let instruction = Box::new(DepositObligationCollateralV2CpiBuilderInstruction {
      __program: program,
              owner: None,
              obligation: None,
              lending_market: None,
              deposit_reserve: None,
              reserve_destination_collateral: None,
              user_source_collateral: None,
              token_program: None,
              instruction_sysvar_account: None,
              lending_market_authority: None,
              obligation_farm_user_state: None,
              reserve_farm_state: None,
              farms_program: None,
                                            collateral_amount: None,
                    __remaining_accounts: Vec::new(),
    });
    Self { instruction }
  }
      #[inline(always)]
    pub fn owner(&mut self, owner: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.owner = Some(owner);
                    self
    }
      #[inline(always)]
    pub fn obligation(&mut self, obligation: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.obligation = Some(obligation);
                    self
    }
      #[inline(always)]
    pub fn lending_market(&mut self, lending_market: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.lending_market = Some(lending_market);
                    self
    }
      #[inline(always)]
    pub fn deposit_reserve(&mut self, deposit_reserve: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.deposit_reserve = Some(deposit_reserve);
                    self
    }
      #[inline(always)]
    pub fn reserve_destination_collateral(&mut self, reserve_destination_collateral: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.reserve_destination_collateral = Some(reserve_destination_collateral);
                    self
    }
      #[inline(always)]
    pub fn user_source_collateral(&mut self, user_source_collateral: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.user_source_collateral = Some(user_source_collateral);
                    self
    }
      #[inline(always)]
    pub fn token_program(&mut self, token_program: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.token_program = Some(token_program);
                    self
    }
      #[inline(always)]
    pub fn instruction_sysvar_account(&mut self, instruction_sysvar_account: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.instruction_sysvar_account = Some(instruction_sysvar_account);
                    self
    }
      #[inline(always)]
    pub fn lending_market_authority(&mut self, lending_market_authority: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.lending_market_authority = Some(lending_market_authority);
                    self
    }
      /// `[optional account]`
#[inline(always)]
    pub fn obligation_farm_user_state(&mut self, obligation_farm_user_state: Option<&'b solana_program::account_info::AccountInfo<'a>>) -> &mut Self {
                        self.instruction.obligation_farm_user_state = obligation_farm_user_state;
                    self
    }
      /// `[optional account]`
#[inline(always)]
    pub fn reserve_farm_state(&mut self, reserve_farm_state: Option<&'b solana_program::account_info::AccountInfo<'a>>) -> &mut Self {
                        self.instruction.reserve_farm_state = reserve_farm_state;
                    self
    }
      #[inline(always)]
    pub fn farms_program(&mut self, farms_program: &'b solana_program::account_info::AccountInfo<'a>) -> &mut Self {
                        self.instruction.farms_program = Some(farms_program);
                    self
    }
                    #[inline(always)]
      pub fn collateral_amount(&mut self, collateral_amount: u64) -> &mut Self {
        self.instruction.collateral_amount = Some(collateral_amount);
        self
      }
        /// Add an additional account to the instruction.
  #[inline(always)]
  pub fn add_remaining_account(&mut self, account: &'b solana_program::account_info::AccountInfo<'a>, is_writable: bool, is_signer: bool) -> &mut Self {
    self.instruction.__remaining_accounts.push((account, is_writable, is_signer));
    self
  }
  /// Add additional accounts to the instruction.
  ///
  /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
  /// and a `bool` indicating whether the account is a signer or not.
  #[inline(always)]
  pub fn add_remaining_accounts(&mut self, accounts: &[(&'b solana_program::account_info::AccountInfo<'a>, bool, bool)]) -> &mut Self {
    self.instruction.__remaining_accounts.extend_from_slice(accounts);
    self
  }
  #[inline(always)]
  pub fn invoke(&self) -> solana_program::entrypoint::ProgramResult {
    self.invoke_signed(&[])
  }
  #[allow(clippy::clone_on_copy)]
  #[allow(clippy::vec_init_then_push)]
  pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program::entrypoint::ProgramResult {
          let args = DepositObligationCollateralV2InstructionArgs {
                                                              collateral_amount: self.instruction.collateral_amount.clone().expect("collateral_amount is not set"),
                                    };
        let instruction = DepositObligationCollateralV2Cpi {
        __program: self.instruction.__program,
                  
          owner: self.instruction.owner.expect("owner is not set"),
                  
          obligation: self.instruction.obligation.expect("obligation is not set"),
                  
          lending_market: self.instruction.lending_market.expect("lending_market is not set"),
                  
          deposit_reserve: self.instruction.deposit_reserve.expect("deposit_reserve is not set"),
                  
          reserve_destination_collateral: self.instruction.reserve_destination_collateral.expect("reserve_destination_collateral is not set"),
                  
          user_source_collateral: self.instruction.user_source_collateral.expect("user_source_collateral is not set"),
                  
          token_program: self.instruction.token_program.expect("token_program is not set"),
                  
          instruction_sysvar_account: self.instruction.instruction_sysvar_account.expect("instruction_sysvar_account is not set"),
                  
          lending_market_authority: self.instruction.lending_market_authority.expect("lending_market_authority is not set"),
                  
          obligation_farm_user_state: self.instruction.obligation_farm_user_state,
                  
          reserve_farm_state: self.instruction.reserve_farm_state,
                  
          farms_program: self.instruction.farms_program.expect("farms_program is not set"),
                          __args: args,
            };
    instruction.invoke_signed_with_remaining_accounts(signers_seeds, &self.instruction.__remaining_accounts)
  }
}

#[derive(Clone, Debug)]
struct DepositObligationCollateralV2CpiBuilderInstruction<'a, 'b> {
  __program: &'b solana_program::account_info::AccountInfo<'a>,
            owner: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                obligation: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                lending_market: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                deposit_reserve: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                reserve_destination_collateral: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                user_source_collateral: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                token_program: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                instruction_sysvar_account: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                lending_market_authority: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                obligation_farm_user_state: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                reserve_farm_state: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                farms_program: Option<&'b solana_program::account_info::AccountInfo<'a>>,
                        collateral_amount: Option<u64>,
        /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
  __remaining_accounts: Vec<(&'b solana_program::account_info::AccountInfo<'a>, bool, bool)>,
}

