[package]
name = "shipstern-block-meta-parser"
description = "Shipstern block meta parser."
readme = "./../../README.md"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yellowstone-grpc-proto = { workspace = true }
shipstern-core = { workspace = true }
shipstern-proc-macro = { workspace = true }
prost = { workspace = true, optional = true }
prost-types = { workspace = true, optional = true }

[dev-dependencies]
shipstern-mock = { workspace = true }
tokio.workspace = true

[features]
default = []
proto = ["dep:prost", "dep:prost-types", "shipstern-core/proto", "shipstern-proc-macro/proto"]
