[package]
name = "shipstern-parser"
description = "Shipstern program parser utilties."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shipstern-core = { workspace = true }
solana-program-option = { workspace = true, optional = true }
solana-pubkey = { workspace = true }
shipstern-proto = { workspace = true, features = [
  "parser",
], optional = true }
thiserror.workspace = true
bs58.workspace = true
base64 = { workspace = true }

[dev-dependencies]
shipstern-mock = { workspace = true }
tokio.workspace = true

[features]
default = []
proto = [
  "dep:shipstern-proto",
  "shipstern-core/proto",
  "shipstern-proto/parser",
  "solana-program-option",
]
