[package]
name = "shipstern-yellowstone-grpc-source"
version.workspace = true
edition.workspace = true
description = "Yellowstone gRPC source for Shipstern"
license.workspace = true
repository.workspace = true
authors.workspace = true
readme = "./README.md"

[dependencies]
async-trait = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "signal", "macros", "sync", "time"] }
tracing = { workspace = true }
futures-util = { workspace = true, features = ["sink"] }
shipstern = { workspace = true }
shipstern-core = { workspace = true }
yellowstone-grpc-proto = { workspace = true }
yellowstone-grpc-client = { workspace = true }
serde = { workspace = true, features = ["derive"] }
clap = { workspace = true, features = ["derive", "cargo", "wrap_help"] }

[dev-dependencies]
toml = { workspace = true }
