//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

pub(crate) mod r#add_operators;
pub(crate) mod r#buy_token;
pub(crate) mod r#cancel_authority_transfer;
pub(crate) mod r#close_bonding_curve_vault;
pub(crate) mod r#collect_trading_fees;
pub(crate) mod r#complete_authority_transfer;
pub(crate) mod r#create_raydium_pool;
pub(crate) mod r#create_raydium_random_pool;
pub(crate) mod r#create_token;
pub(crate) mod r#create_token_fallback;
pub(crate) mod r#deploy_bonding_curve;
pub(crate) mod r#deploy_bonding_curve_fallback;
pub(crate) mod r#deposit_into_raydium;
pub(crate) mod r#graduate;
pub(crate) mod r#initialize;
pub(crate) mod r#initiate_authority_transfer;
pub(crate) mod r#lock_raydium_liquidity;
pub(crate) mod r#remove_operators;
pub(crate) mod r#sell_token;
pub(crate) mod r#split_trading_fees;
pub(crate) mod r#swap_sol_for_tokens_on_raydium;
pub(crate) mod r#swap_tokens_for_sol_on_raydium;
pub(crate) mod r#toggle_paused;
pub(crate) mod r#update_config;

pub use self::r#add_operators::*;
pub use self::r#buy_token::*;
pub use self::r#cancel_authority_transfer::*;
pub use self::r#close_bonding_curve_vault::*;
pub use self::r#collect_trading_fees::*;
pub use self::r#complete_authority_transfer::*;
pub use self::r#create_raydium_pool::*;
pub use self::r#create_raydium_random_pool::*;
pub use self::r#create_token::*;
pub use self::r#create_token_fallback::*;
pub use self::r#deploy_bonding_curve::*;
pub use self::r#deploy_bonding_curve_fallback::*;
pub use self::r#deposit_into_raydium::*;
pub use self::r#graduate::*;
pub use self::r#initialize::*;
pub use self::r#initiate_authority_transfer::*;
pub use self::r#lock_raydium_liquidity::*;
pub use self::r#remove_operators::*;
pub use self::r#sell_token::*;
pub use self::r#split_trading_fees::*;
pub use self::r#swap_sol_for_tokens_on_raydium::*;
pub use self::r#swap_tokens_for_sol_on_raydium::*;
pub use self::r#toggle_paused::*;
pub use self::r#update_config::*;
