//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use crate::generated::types::PriceHeuristic;
use crate::generated::types::ScopeConfiguration;
use crate::generated::types::SwitchboardConfiguration;
use crate::generated::types::PythConfiguration;
use borsh::BorshSerialize;
use borsh::BorshDeserialize;

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct TokenInfo {
/// UTF-8 encoded name of the token (null-terminated)
pub name: [u8; 32],
/// Heuristics limits of acceptable price
pub heuristic: PriceHeuristic,
/// Max divergence between twap and price in bps
pub max_twap_divergence_bps: u64,
pub max_age_price_seconds: u64,
pub max_age_twap_seconds: u64,
/// Scope price configuration
pub scope_configuration: ScopeConfiguration,
/// Switchboard configuration
pub switchboard_configuration: SwitchboardConfiguration,
/// Pyth configuration
pub pyth_configuration: PythConfiguration,
pub block_price_usage: u8,
pub reserved: [u8; 7],
pub padding: [u64; 19],
}


