//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

pub(crate) mod r#global_config;
pub(crate) mod r#platform_config;
pub(crate) mod r#pool_state;
pub(crate) mod r#vesting_record;

pub use self::{r#global_config::*, r#platform_config::*, r#pool_state::*, r#vesting_record::*};
