[package]
name = "shipstern-example-filtered-pipeline"
description = "Example of filtered pipeline"
publish = false
edition.workspace = true
license = "MIT"
repository = "https://github.com/rpcpool/shipstern"

[dependencies]
clap = { workspace = true, features = ["derive", "cargo", "wrap_help"] }
toml = { workspace = true }
tracing = { workspace = true }
rustls = { workspace = true }
shipstern = { workspace = true }
shipstern-spl-token-parser = { workspace = true }

shipstern-yellowstone-grpc-source = { workspace = true }
shipstern-solana-rpc-source = { workspace = true }
