//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::{BorshDeserialize, BorshSerialize};

/// Accounts.
#[derive(Debug)]
pub struct ClaimFees {
    pub payer: solana_pubkey::Pubkey,

    pub vpool: solana_pubkey::Pubkey,

    pub virtuals_mint: solana_pubkey::Pubkey,

    pub token_mint: solana_pubkey::Pubkey,

    pub vpool_virtuals_ata: solana_pubkey::Pubkey,

    pub vpool_token_ata: solana_pubkey::Pubkey,

    pub platform: solana_pubkey::Pubkey,

    pub platform_virtuals_ata: solana_pubkey::Pubkey,

    pub platform_token_ata: solana_pubkey::Pubkey,

    pub creator_virtuals_ata: solana_pubkey::Pubkey,

    pub creator_token_ata: solana_pubkey::Pubkey,

    pub pool: solana_pubkey::Pubkey,

    pub lp_mint: solana_pubkey::Pubkey,

    pub lock_escrow: solana_pubkey::Pubkey,

    pub escrow_vault: solana_pubkey::Pubkey,

    pub token_program: solana_pubkey::Pubkey,

    pub virtuals_vault: solana_pubkey::Pubkey,

    pub token_vault: solana_pubkey::Pubkey,

    pub virtuals_token_vault: solana_pubkey::Pubkey,

    pub token_token_vault: solana_pubkey::Pubkey,

    pub virtuals_vault_lp_mint: solana_pubkey::Pubkey,

    pub token_vault_lp_mint: solana_pubkey::Pubkey,

    pub virtuals_vault_lp: solana_pubkey::Pubkey,

    pub token_vault_lp: solana_pubkey::Pubkey,

    pub vault_program: solana_pubkey::Pubkey,

    pub associated_token_program: solana_pubkey::Pubkey,

    pub system_program: solana_pubkey::Pubkey,

    pub dynamic_amm_program: solana_pubkey::Pubkey,
}

impl ClaimFees {
    pub fn instruction(&self) -> solana_instruction::Instruction {
        self.instruction_with_remaining_accounts(&[])
    }

    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::vec_init_then_push)]
    pub fn instruction_with_remaining_accounts(
        &self,
        remaining_accounts: &[solana_instruction::AccountMeta],
    ) -> solana_instruction::Instruction {
        let mut accounts = Vec::with_capacity(28 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new(self.payer, true));
        accounts.push(solana_instruction::AccountMeta::new(self.vpool, false));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.virtuals_mint,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.token_mint,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.vpool_virtuals_ata,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.vpool_token_ata,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(self.platform, false));
        accounts.push(solana_instruction::AccountMeta::new(
            self.platform_virtuals_ata,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.platform_token_ata,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.creator_virtuals_ata,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.creator_token_ata,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(self.pool, false));
        accounts.push(solana_instruction::AccountMeta::new(self.lp_mint, false));
        accounts.push(solana_instruction::AccountMeta::new(
            self.lock_escrow,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.escrow_vault,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.token_program,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.virtuals_vault,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.token_vault,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.virtuals_token_vault,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.token_token_vault,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.virtuals_vault_lp_mint,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.token_vault_lp_mint,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.virtuals_vault_lp,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.token_vault_lp,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.vault_program,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.associated_token_program,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.system_program,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.dynamic_amm_program,
            false,
        ));
        accounts.extend_from_slice(remaining_accounts);
        let data = borsh::to_vec(&ClaimFeesInstructionData::new()).unwrap();

        solana_instruction::Instruction {
            program_id: crate::VIRTUALS_PROGRAM_ID,
            accounts,
            data,
        }
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct ClaimFeesInstructionData {
    discriminator: [u8; 8],
}

impl ClaimFeesInstructionData {
    pub fn new() -> Self {
        Self {
            discriminator: [82, 251, 233, 156, 12, 52, 184, 202],
        }
    }
}

impl Default for ClaimFeesInstructionData {
    fn default() -> Self {
        Self::new()
    }
}

/// Instruction builder for `ClaimFees`.
///
/// ### Accounts:
///
///   0. `[writable, signer]` payer
///   1. `[writable]` vpool
///   2. `[optional]` virtuals_mint (default to `3iQL8BFS2vE7mww4ehAqQHAsbmRNCrPxizWAT2Zfyr9y`)
///   3. `[]` token_mint
///   4. `[writable]` vpool_virtuals_ata
///   5. `[writable]` vpool_token_ata
///   6. `[writable, optional]` platform (default to `FxKXqCKXdxPbfYau83ZkGUXgcZWhKBTfAjGg2KzYSopS`)
///   7. `[writable]` platform_virtuals_ata
///   8. `[writable]` platform_token_ata
///   9. `[writable]` creator_virtuals_ata
///   10. `[writable]` creator_token_ata
///   11. `[writable]` pool
///   12. `[writable]` lp_mint
///   13. `[writable]` lock_escrow
///   14. `[writable]` escrow_vault
///   15. `[optional]` token_program (default to `TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA`)
///   16. `[writable]` virtuals_vault
///   17. `[writable]` token_vault
///   18. `[writable]` virtuals_token_vault
///   19. `[writable]` token_token_vault
///   20. `[writable]` virtuals_vault_lp_mint
///   21. `[writable]` token_vault_lp_mint
///   22. `[writable]` virtuals_vault_lp
///   23. `[writable]` token_vault_lp
///   24. `[optional]` vault_program (default to `24Uqj9JCLxUeoC3hGfh5W3s9FM9uCHDS2SG3LYwBpyTi`)
///   25. `[optional]` associated_token_program (default to `ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL`)
///   26. `[optional]` system_program (default to `11111111111111111111111111111111`)
///   27. `[optional]` dynamic_amm_program (default to `Eo7WjKq67rjJQSZxS6z3YkapzY3eMj6Xy8X5EQVn5UaB`)
#[derive(Clone, Debug, Default)]
pub struct ClaimFeesBuilder {
    payer: Option<solana_pubkey::Pubkey>,
    vpool: Option<solana_pubkey::Pubkey>,
    virtuals_mint: Option<solana_pubkey::Pubkey>,
    token_mint: Option<solana_pubkey::Pubkey>,
    vpool_virtuals_ata: Option<solana_pubkey::Pubkey>,
    vpool_token_ata: Option<solana_pubkey::Pubkey>,
    platform: Option<solana_pubkey::Pubkey>,
    platform_virtuals_ata: Option<solana_pubkey::Pubkey>,
    platform_token_ata: Option<solana_pubkey::Pubkey>,
    creator_virtuals_ata: Option<solana_pubkey::Pubkey>,
    creator_token_ata: Option<solana_pubkey::Pubkey>,
    pool: Option<solana_pubkey::Pubkey>,
    lp_mint: Option<solana_pubkey::Pubkey>,
    lock_escrow: Option<solana_pubkey::Pubkey>,
    escrow_vault: Option<solana_pubkey::Pubkey>,
    token_program: Option<solana_pubkey::Pubkey>,
    virtuals_vault: Option<solana_pubkey::Pubkey>,
    token_vault: Option<solana_pubkey::Pubkey>,
    virtuals_token_vault: Option<solana_pubkey::Pubkey>,
    token_token_vault: Option<solana_pubkey::Pubkey>,
    virtuals_vault_lp_mint: Option<solana_pubkey::Pubkey>,
    token_vault_lp_mint: Option<solana_pubkey::Pubkey>,
    virtuals_vault_lp: Option<solana_pubkey::Pubkey>,
    token_vault_lp: Option<solana_pubkey::Pubkey>,
    vault_program: Option<solana_pubkey::Pubkey>,
    associated_token_program: Option<solana_pubkey::Pubkey>,
    system_program: Option<solana_pubkey::Pubkey>,
    dynamic_amm_program: Option<solana_pubkey::Pubkey>,
    __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl ClaimFeesBuilder {
    pub fn new() -> Self {
        Self::default()
    }

    #[inline(always)]
    pub fn payer(&mut self, payer: solana_pubkey::Pubkey) -> &mut Self {
        self.payer = Some(payer);
        self
    }

    #[inline(always)]
    pub fn vpool(&mut self, vpool: solana_pubkey::Pubkey) -> &mut Self {
        self.vpool = Some(vpool);
        self
    }

    /// `[optional account, default to '3iQL8BFS2vE7mww4ehAqQHAsbmRNCrPxizWAT2Zfyr9y']`
    #[inline(always)]
    pub fn virtuals_mint(&mut self, virtuals_mint: solana_pubkey::Pubkey) -> &mut Self {
        self.virtuals_mint = Some(virtuals_mint);
        self
    }

    #[inline(always)]
    pub fn token_mint(&mut self, token_mint: solana_pubkey::Pubkey) -> &mut Self {
        self.token_mint = Some(token_mint);
        self
    }

    #[inline(always)]
    pub fn vpool_virtuals_ata(&mut self, vpool_virtuals_ata: solana_pubkey::Pubkey) -> &mut Self {
        self.vpool_virtuals_ata = Some(vpool_virtuals_ata);
        self
    }

    #[inline(always)]
    pub fn vpool_token_ata(&mut self, vpool_token_ata: solana_pubkey::Pubkey) -> &mut Self {
        self.vpool_token_ata = Some(vpool_token_ata);
        self
    }

    /// `[optional account, default to 'FxKXqCKXdxPbfYau83ZkGUXgcZWhKBTfAjGg2KzYSopS']`
    #[inline(always)]
    pub fn platform(&mut self, platform: solana_pubkey::Pubkey) -> &mut Self {
        self.platform = Some(platform);
        self
    }

    #[inline(always)]
    pub fn platform_virtuals_ata(
        &mut self,
        platform_virtuals_ata: solana_pubkey::Pubkey,
    ) -> &mut Self {
        self.platform_virtuals_ata = Some(platform_virtuals_ata);
        self
    }

    #[inline(always)]
    pub fn platform_token_ata(&mut self, platform_token_ata: solana_pubkey::Pubkey) -> &mut Self {
        self.platform_token_ata = Some(platform_token_ata);
        self
    }

    #[inline(always)]
    pub fn creator_virtuals_ata(
        &mut self,
        creator_virtuals_ata: solana_pubkey::Pubkey,
    ) -> &mut Self {
        self.creator_virtuals_ata = Some(creator_virtuals_ata);
        self
    }

    #[inline(always)]
    pub fn creator_token_ata(&mut self, creator_token_ata: solana_pubkey::Pubkey) -> &mut Self {
        self.creator_token_ata = Some(creator_token_ata);
        self
    }

    #[inline(always)]
    pub fn pool(&mut self, pool: solana_pubkey::Pubkey) -> &mut Self {
        self.pool = Some(pool);
        self
    }

    #[inline(always)]
    pub fn lp_mint(&mut self, lp_mint: solana_pubkey::Pubkey) -> &mut Self {
        self.lp_mint = Some(lp_mint);
        self
    }

    #[inline(always)]
    pub fn lock_escrow(&mut self, lock_escrow: solana_pubkey::Pubkey) -> &mut Self {
        self.lock_escrow = Some(lock_escrow);
        self
    }

    #[inline(always)]
    pub fn escrow_vault(&mut self, escrow_vault: solana_pubkey::Pubkey) -> &mut Self {
        self.escrow_vault = Some(escrow_vault);
        self
    }

    /// `[optional account, default to 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA']`
    #[inline(always)]
    pub fn token_program(&mut self, token_program: solana_pubkey::Pubkey) -> &mut Self {
        self.token_program = Some(token_program);
        self
    }

    #[inline(always)]
    pub fn virtuals_vault(&mut self, virtuals_vault: solana_pubkey::Pubkey) -> &mut Self {
        self.virtuals_vault = Some(virtuals_vault);
        self
    }

    #[inline(always)]
    pub fn token_vault(&mut self, token_vault: solana_pubkey::Pubkey) -> &mut Self {
        self.token_vault = Some(token_vault);
        self
    }

    #[inline(always)]
    pub fn virtuals_token_vault(
        &mut self,
        virtuals_token_vault: solana_pubkey::Pubkey,
    ) -> &mut Self {
        self.virtuals_token_vault = Some(virtuals_token_vault);
        self
    }

    #[inline(always)]
    pub fn token_token_vault(&mut self, token_token_vault: solana_pubkey::Pubkey) -> &mut Self {
        self.token_token_vault = Some(token_token_vault);
        self
    }

    #[inline(always)]
    pub fn virtuals_vault_lp_mint(
        &mut self,
        virtuals_vault_lp_mint: solana_pubkey::Pubkey,
    ) -> &mut Self {
        self.virtuals_vault_lp_mint = Some(virtuals_vault_lp_mint);
        self
    }

    #[inline(always)]
    pub fn token_vault_lp_mint(&mut self, token_vault_lp_mint: solana_pubkey::Pubkey) -> &mut Self {
        self.token_vault_lp_mint = Some(token_vault_lp_mint);
        self
    }

    #[inline(always)]
    pub fn virtuals_vault_lp(&mut self, virtuals_vault_lp: solana_pubkey::Pubkey) -> &mut Self {
        self.virtuals_vault_lp = Some(virtuals_vault_lp);
        self
    }

    #[inline(always)]
    pub fn token_vault_lp(&mut self, token_vault_lp: solana_pubkey::Pubkey) -> &mut Self {
        self.token_vault_lp = Some(token_vault_lp);
        self
    }

    /// `[optional account, default to '24Uqj9JCLxUeoC3hGfh5W3s9FM9uCHDS2SG3LYwBpyTi']`
    #[inline(always)]
    pub fn vault_program(&mut self, vault_program: solana_pubkey::Pubkey) -> &mut Self {
        self.vault_program = Some(vault_program);
        self
    }

    /// `[optional account, default to 'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL']`
    #[inline(always)]
    pub fn associated_token_program(
        &mut self,
        associated_token_program: solana_pubkey::Pubkey,
    ) -> &mut Self {
        self.associated_token_program = Some(associated_token_program);
        self
    }

    /// `[optional account, default to '11111111111111111111111111111111']`
    #[inline(always)]
    pub fn system_program(&mut self, system_program: solana_pubkey::Pubkey) -> &mut Self {
        self.system_program = Some(system_program);
        self
    }

    /// `[optional account, default to 'Eo7WjKq67rjJQSZxS6z3YkapzY3eMj6Xy8X5EQVn5UaB']`
    #[inline(always)]
    pub fn dynamic_amm_program(&mut self, dynamic_amm_program: solana_pubkey::Pubkey) -> &mut Self {
        self.dynamic_amm_program = Some(dynamic_amm_program);
        self
    }

    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
        self.__remaining_accounts.push(account);
        self
    }

    /// Add additional accounts to the instruction.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[solana_instruction::AccountMeta],
    ) -> &mut Self {
        self.__remaining_accounts.extend_from_slice(accounts);
        self
    }

    #[allow(clippy::clone_on_copy)]
    pub fn instruction(&self) -> solana_instruction::Instruction {
        let accounts = ClaimFees {
            payer: self.payer.expect("payer is not set"),
            vpool: self.vpool.expect("vpool is not set"),
            virtuals_mint: self.virtuals_mint.unwrap_or(solana_pubkey::pubkey!(
                "3iQL8BFS2vE7mww4ehAqQHAsbmRNCrPxizWAT2Zfyr9y"
            )),
            token_mint: self.token_mint.expect("token_mint is not set"),
            vpool_virtuals_ata: self
                .vpool_virtuals_ata
                .expect("vpool_virtuals_ata is not set"),
            vpool_token_ata: self.vpool_token_ata.expect("vpool_token_ata is not set"),
            platform: self.platform.unwrap_or(solana_pubkey::pubkey!(
                "FxKXqCKXdxPbfYau83ZkGUXgcZWhKBTfAjGg2KzYSopS"
            )),
            platform_virtuals_ata: self
                .platform_virtuals_ata
                .expect("platform_virtuals_ata is not set"),
            platform_token_ata: self
                .platform_token_ata
                .expect("platform_token_ata is not set"),
            creator_virtuals_ata: self
                .creator_virtuals_ata
                .expect("creator_virtuals_ata is not set"),
            creator_token_ata: self
                .creator_token_ata
                .expect("creator_token_ata is not set"),
            pool: self.pool.expect("pool is not set"),
            lp_mint: self.lp_mint.expect("lp_mint is not set"),
            lock_escrow: self.lock_escrow.expect("lock_escrow is not set"),
            escrow_vault: self.escrow_vault.expect("escrow_vault is not set"),
            token_program: self.token_program.unwrap_or(solana_pubkey::pubkey!(
                "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
            )),
            virtuals_vault: self.virtuals_vault.expect("virtuals_vault is not set"),
            token_vault: self.token_vault.expect("token_vault is not set"),
            virtuals_token_vault: self
                .virtuals_token_vault
                .expect("virtuals_token_vault is not set"),
            token_token_vault: self
                .token_token_vault
                .expect("token_token_vault is not set"),
            virtuals_vault_lp_mint: self
                .virtuals_vault_lp_mint
                .expect("virtuals_vault_lp_mint is not set"),
            token_vault_lp_mint: self
                .token_vault_lp_mint
                .expect("token_vault_lp_mint is not set"),
            virtuals_vault_lp: self
                .virtuals_vault_lp
                .expect("virtuals_vault_lp is not set"),
            token_vault_lp: self.token_vault_lp.expect("token_vault_lp is not set"),
            vault_program: self.vault_program.unwrap_or(solana_pubkey::pubkey!(
                "24Uqj9JCLxUeoC3hGfh5W3s9FM9uCHDS2SG3LYwBpyTi"
            )),
            associated_token_program: self.associated_token_program.unwrap_or(
                solana_pubkey::pubkey!("ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"),
            ),
            system_program: self
                .system_program
                .unwrap_or(solana_pubkey::pubkey!("11111111111111111111111111111111")),
            dynamic_amm_program: self.dynamic_amm_program.unwrap_or(solana_pubkey::pubkey!(
                "Eo7WjKq67rjJQSZxS6z3YkapzY3eMj6Xy8X5EQVn5UaB"
            )),
        };

        accounts.instruction_with_remaining_accounts(&self.__remaining_accounts)
    }
}

/// `claim_fees` CPI accounts.
pub struct ClaimFeesCpiAccounts<'a, 'b> {
    pub payer: &'b solana_account_info::AccountInfo<'a>,

    pub vpool: &'b solana_account_info::AccountInfo<'a>,

    pub virtuals_mint: &'b solana_account_info::AccountInfo<'a>,

    pub token_mint: &'b solana_account_info::AccountInfo<'a>,

    pub vpool_virtuals_ata: &'b solana_account_info::AccountInfo<'a>,

    pub vpool_token_ata: &'b solana_account_info::AccountInfo<'a>,

    pub platform: &'b solana_account_info::AccountInfo<'a>,

    pub platform_virtuals_ata: &'b solana_account_info::AccountInfo<'a>,

    pub platform_token_ata: &'b solana_account_info::AccountInfo<'a>,

    pub creator_virtuals_ata: &'b solana_account_info::AccountInfo<'a>,

    pub creator_token_ata: &'b solana_account_info::AccountInfo<'a>,

    pub pool: &'b solana_account_info::AccountInfo<'a>,

    pub lp_mint: &'b solana_account_info::AccountInfo<'a>,

    pub lock_escrow: &'b solana_account_info::AccountInfo<'a>,

    pub escrow_vault: &'b solana_account_info::AccountInfo<'a>,

    pub token_program: &'b solana_account_info::AccountInfo<'a>,

    pub virtuals_vault: &'b solana_account_info::AccountInfo<'a>,

    pub token_vault: &'b solana_account_info::AccountInfo<'a>,

    pub virtuals_token_vault: &'b solana_account_info::AccountInfo<'a>,

    pub token_token_vault: &'b solana_account_info::AccountInfo<'a>,

    pub virtuals_vault_lp_mint: &'b solana_account_info::AccountInfo<'a>,

    pub token_vault_lp_mint: &'b solana_account_info::AccountInfo<'a>,

    pub virtuals_vault_lp: &'b solana_account_info::AccountInfo<'a>,

    pub token_vault_lp: &'b solana_account_info::AccountInfo<'a>,

    pub vault_program: &'b solana_account_info::AccountInfo<'a>,

    pub associated_token_program: &'b solana_account_info::AccountInfo<'a>,

    pub system_program: &'b solana_account_info::AccountInfo<'a>,

    pub dynamic_amm_program: &'b solana_account_info::AccountInfo<'a>,
}

/// `claim_fees` CPI instruction.
pub struct ClaimFeesCpi<'a, 'b> {
    /// The program to invoke.
    pub __program: &'b solana_account_info::AccountInfo<'a>,

    pub payer: &'b solana_account_info::AccountInfo<'a>,

    pub vpool: &'b solana_account_info::AccountInfo<'a>,

    pub virtuals_mint: &'b solana_account_info::AccountInfo<'a>,

    pub token_mint: &'b solana_account_info::AccountInfo<'a>,

    pub vpool_virtuals_ata: &'b solana_account_info::AccountInfo<'a>,

    pub vpool_token_ata: &'b solana_account_info::AccountInfo<'a>,

    pub platform: &'b solana_account_info::AccountInfo<'a>,

    pub platform_virtuals_ata: &'b solana_account_info::AccountInfo<'a>,

    pub platform_token_ata: &'b solana_account_info::AccountInfo<'a>,

    pub creator_virtuals_ata: &'b solana_account_info::AccountInfo<'a>,

    pub creator_token_ata: &'b solana_account_info::AccountInfo<'a>,

    pub pool: &'b solana_account_info::AccountInfo<'a>,

    pub lp_mint: &'b solana_account_info::AccountInfo<'a>,

    pub lock_escrow: &'b solana_account_info::AccountInfo<'a>,

    pub escrow_vault: &'b solana_account_info::AccountInfo<'a>,

    pub token_program: &'b solana_account_info::AccountInfo<'a>,

    pub virtuals_vault: &'b solana_account_info::AccountInfo<'a>,

    pub token_vault: &'b solana_account_info::AccountInfo<'a>,

    pub virtuals_token_vault: &'b solana_account_info::AccountInfo<'a>,

    pub token_token_vault: &'b solana_account_info::AccountInfo<'a>,

    pub virtuals_vault_lp_mint: &'b solana_account_info::AccountInfo<'a>,

    pub token_vault_lp_mint: &'b solana_account_info::AccountInfo<'a>,

    pub virtuals_vault_lp: &'b solana_account_info::AccountInfo<'a>,

    pub token_vault_lp: &'b solana_account_info::AccountInfo<'a>,

    pub vault_program: &'b solana_account_info::AccountInfo<'a>,

    pub associated_token_program: &'b solana_account_info::AccountInfo<'a>,

    pub system_program: &'b solana_account_info::AccountInfo<'a>,

    pub dynamic_amm_program: &'b solana_account_info::AccountInfo<'a>,
}

impl<'a, 'b> ClaimFeesCpi<'a, 'b> {
    pub fn new(
        program: &'b solana_account_info::AccountInfo<'a>,
        accounts: ClaimFeesCpiAccounts<'a, 'b>,
    ) -> Self {
        Self {
            __program: program,
            payer: accounts.payer,
            vpool: accounts.vpool,
            virtuals_mint: accounts.virtuals_mint,
            token_mint: accounts.token_mint,
            vpool_virtuals_ata: accounts.vpool_virtuals_ata,
            vpool_token_ata: accounts.vpool_token_ata,
            platform: accounts.platform,
            platform_virtuals_ata: accounts.platform_virtuals_ata,
            platform_token_ata: accounts.platform_token_ata,
            creator_virtuals_ata: accounts.creator_virtuals_ata,
            creator_token_ata: accounts.creator_token_ata,
            pool: accounts.pool,
            lp_mint: accounts.lp_mint,
            lock_escrow: accounts.lock_escrow,
            escrow_vault: accounts.escrow_vault,
            token_program: accounts.token_program,
            virtuals_vault: accounts.virtuals_vault,
            token_vault: accounts.token_vault,
            virtuals_token_vault: accounts.virtuals_token_vault,
            token_token_vault: accounts.token_token_vault,
            virtuals_vault_lp_mint: accounts.virtuals_vault_lp_mint,
            token_vault_lp_mint: accounts.token_vault_lp_mint,
            virtuals_vault_lp: accounts.virtuals_vault_lp,
            token_vault_lp: accounts.token_vault_lp,
            vault_program: accounts.vault_program,
            associated_token_program: accounts.associated_token_program,
            system_program: accounts.system_program,
            dynamic_amm_program: accounts.dynamic_amm_program,
        }
    }

    #[inline(always)]
    pub fn invoke(&self) -> solana_program_entrypoint::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], &[])
    }

    #[inline(always)]
    pub fn invoke_with_remaining_accounts(
        &self,
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_entrypoint::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
    }

    #[inline(always)]
    pub fn invoke_signed(
        &self,
        signers_seeds: &[&[&[u8]]],
    ) -> solana_program_entrypoint::ProgramResult {
        self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
    }

    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed_with_remaining_accounts(
        &self,
        signers_seeds: &[&[&[u8]]],
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_entrypoint::ProgramResult {
        let mut accounts = Vec::with_capacity(28 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new(*self.payer.key, true));
        accounts.push(solana_instruction::AccountMeta::new(*self.vpool.key, false));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.virtuals_mint.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.token_mint.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.vpool_virtuals_ata.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.vpool_token_ata.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.platform.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.platform_virtuals_ata.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.platform_token_ata.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.creator_virtuals_ata.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.creator_token_ata.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(*self.pool.key, false));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.lp_mint.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.lock_escrow.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.escrow_vault.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.token_program.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.virtuals_vault.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.token_vault.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.virtuals_token_vault.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.token_token_vault.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.virtuals_vault_lp_mint.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.token_vault_lp_mint.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.virtuals_vault_lp.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.token_vault_lp.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.vault_program.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.associated_token_program.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.system_program.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.dynamic_amm_program.key,
            false,
        ));
        remaining_accounts.iter().for_each(|remaining_account| {
            accounts.push(solana_instruction::AccountMeta {
                pubkey: *remaining_account.0.key,
                is_signer: remaining_account.1,
                is_writable: remaining_account.2,
            })
        });
        let data = borsh::to_vec(&ClaimFeesInstructionData::new()).unwrap();

        let instruction = solana_instruction::Instruction {
            program_id: crate::VIRTUALS_PROGRAM_ID,
            accounts,
            data,
        };
        let mut account_infos = Vec::with_capacity(29 + remaining_accounts.len());
        account_infos.push(self.__program.clone());
        account_infos.push(self.payer.clone());
        account_infos.push(self.vpool.clone());
        account_infos.push(self.virtuals_mint.clone());
        account_infos.push(self.token_mint.clone());
        account_infos.push(self.vpool_virtuals_ata.clone());
        account_infos.push(self.vpool_token_ata.clone());
        account_infos.push(self.platform.clone());
        account_infos.push(self.platform_virtuals_ata.clone());
        account_infos.push(self.platform_token_ata.clone());
        account_infos.push(self.creator_virtuals_ata.clone());
        account_infos.push(self.creator_token_ata.clone());
        account_infos.push(self.pool.clone());
        account_infos.push(self.lp_mint.clone());
        account_infos.push(self.lock_escrow.clone());
        account_infos.push(self.escrow_vault.clone());
        account_infos.push(self.token_program.clone());
        account_infos.push(self.virtuals_vault.clone());
        account_infos.push(self.token_vault.clone());
        account_infos.push(self.virtuals_token_vault.clone());
        account_infos.push(self.token_token_vault.clone());
        account_infos.push(self.virtuals_vault_lp_mint.clone());
        account_infos.push(self.token_vault_lp_mint.clone());
        account_infos.push(self.virtuals_vault_lp.clone());
        account_infos.push(self.token_vault_lp.clone());
        account_infos.push(self.vault_program.clone());
        account_infos.push(self.associated_token_program.clone());
        account_infos.push(self.system_program.clone());
        account_infos.push(self.dynamic_amm_program.clone());
        remaining_accounts
            .iter()
            .for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

        if signers_seeds.is_empty() {
            solana_cpi::invoke(&instruction, &account_infos)
        } else {
            solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
        }
    }
}

/// Instruction builder for `ClaimFees` via CPI.
///
/// ### Accounts:
///
///   0. `[writable, signer]` payer
///   1. `[writable]` vpool
///   2. `[]` virtuals_mint
///   3. `[]` token_mint
///   4. `[writable]` vpool_virtuals_ata
///   5. `[writable]` vpool_token_ata
///   6. `[writable]` platform
///   7. `[writable]` platform_virtuals_ata
///   8. `[writable]` platform_token_ata
///   9. `[writable]` creator_virtuals_ata
///   10. `[writable]` creator_token_ata
///   11. `[writable]` pool
///   12. `[writable]` lp_mint
///   13. `[writable]` lock_escrow
///   14. `[writable]` escrow_vault
///   15. `[]` token_program
///   16. `[writable]` virtuals_vault
///   17. `[writable]` token_vault
///   18. `[writable]` virtuals_token_vault
///   19. `[writable]` token_token_vault
///   20. `[writable]` virtuals_vault_lp_mint
///   21. `[writable]` token_vault_lp_mint
///   22. `[writable]` virtuals_vault_lp
///   23. `[writable]` token_vault_lp
///   24. `[]` vault_program
///   25. `[]` associated_token_program
///   26. `[]` system_program
///   27. `[]` dynamic_amm_program
#[derive(Clone, Debug)]
pub struct ClaimFeesCpiBuilder<'a, 'b> {
    instruction: Box<ClaimFeesCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> ClaimFeesCpiBuilder<'a, 'b> {
    pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
        let instruction = Box::new(ClaimFeesCpiBuilderInstruction {
            __program: program,
            payer: None,
            vpool: None,
            virtuals_mint: None,
            token_mint: None,
            vpool_virtuals_ata: None,
            vpool_token_ata: None,
            platform: None,
            platform_virtuals_ata: None,
            platform_token_ata: None,
            creator_virtuals_ata: None,
            creator_token_ata: None,
            pool: None,
            lp_mint: None,
            lock_escrow: None,
            escrow_vault: None,
            token_program: None,
            virtuals_vault: None,
            token_vault: None,
            virtuals_token_vault: None,
            token_token_vault: None,
            virtuals_vault_lp_mint: None,
            token_vault_lp_mint: None,
            virtuals_vault_lp: None,
            token_vault_lp: None,
            vault_program: None,
            associated_token_program: None,
            system_program: None,
            dynamic_amm_program: None,
            __remaining_accounts: Vec::new(),
        });
        Self { instruction }
    }

    #[inline(always)]
    pub fn payer(&mut self, payer: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.payer = Some(payer);
        self
    }

    #[inline(always)]
    pub fn vpool(&mut self, vpool: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.vpool = Some(vpool);
        self
    }

    #[inline(always)]
    pub fn virtuals_mint(
        &mut self,
        virtuals_mint: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.virtuals_mint = Some(virtuals_mint);
        self
    }

    #[inline(always)]
    pub fn token_mint(
        &mut self,
        token_mint: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.token_mint = Some(token_mint);
        self
    }

    #[inline(always)]
    pub fn vpool_virtuals_ata(
        &mut self,
        vpool_virtuals_ata: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.vpool_virtuals_ata = Some(vpool_virtuals_ata);
        self
    }

    #[inline(always)]
    pub fn vpool_token_ata(
        &mut self,
        vpool_token_ata: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.vpool_token_ata = Some(vpool_token_ata);
        self
    }

    #[inline(always)]
    pub fn platform(&mut self, platform: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.platform = Some(platform);
        self
    }

    #[inline(always)]
    pub fn platform_virtuals_ata(
        &mut self,
        platform_virtuals_ata: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.platform_virtuals_ata = Some(platform_virtuals_ata);
        self
    }

    #[inline(always)]
    pub fn platform_token_ata(
        &mut self,
        platform_token_ata: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.platform_token_ata = Some(platform_token_ata);
        self
    }

    #[inline(always)]
    pub fn creator_virtuals_ata(
        &mut self,
        creator_virtuals_ata: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.creator_virtuals_ata = Some(creator_virtuals_ata);
        self
    }

    #[inline(always)]
    pub fn creator_token_ata(
        &mut self,
        creator_token_ata: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.creator_token_ata = Some(creator_token_ata);
        self
    }

    #[inline(always)]
    pub fn pool(&mut self, pool: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.pool = Some(pool);
        self
    }

    #[inline(always)]
    pub fn lp_mint(&mut self, lp_mint: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.lp_mint = Some(lp_mint);
        self
    }

    #[inline(always)]
    pub fn lock_escrow(
        &mut self,
        lock_escrow: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.lock_escrow = Some(lock_escrow);
        self
    }

    #[inline(always)]
    pub fn escrow_vault(
        &mut self,
        escrow_vault: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.escrow_vault = Some(escrow_vault);
        self
    }

    #[inline(always)]
    pub fn token_program(
        &mut self,
        token_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.token_program = Some(token_program);
        self
    }

    #[inline(always)]
    pub fn virtuals_vault(
        &mut self,
        virtuals_vault: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.virtuals_vault = Some(virtuals_vault);
        self
    }

    #[inline(always)]
    pub fn token_vault(
        &mut self,
        token_vault: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.token_vault = Some(token_vault);
        self
    }

    #[inline(always)]
    pub fn virtuals_token_vault(
        &mut self,
        virtuals_token_vault: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.virtuals_token_vault = Some(virtuals_token_vault);
        self
    }

    #[inline(always)]
    pub fn token_token_vault(
        &mut self,
        token_token_vault: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.token_token_vault = Some(token_token_vault);
        self
    }

    #[inline(always)]
    pub fn virtuals_vault_lp_mint(
        &mut self,
        virtuals_vault_lp_mint: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.virtuals_vault_lp_mint = Some(virtuals_vault_lp_mint);
        self
    }

    #[inline(always)]
    pub fn token_vault_lp_mint(
        &mut self,
        token_vault_lp_mint: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.token_vault_lp_mint = Some(token_vault_lp_mint);
        self
    }

    #[inline(always)]
    pub fn virtuals_vault_lp(
        &mut self,
        virtuals_vault_lp: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.virtuals_vault_lp = Some(virtuals_vault_lp);
        self
    }

    #[inline(always)]
    pub fn token_vault_lp(
        &mut self,
        token_vault_lp: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.token_vault_lp = Some(token_vault_lp);
        self
    }

    #[inline(always)]
    pub fn vault_program(
        &mut self,
        vault_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.vault_program = Some(vault_program);
        self
    }

    #[inline(always)]
    pub fn associated_token_program(
        &mut self,
        associated_token_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.associated_token_program = Some(associated_token_program);
        self
    }

    #[inline(always)]
    pub fn system_program(
        &mut self,
        system_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.system_program = Some(system_program);
        self
    }

    #[inline(always)]
    pub fn dynamic_amm_program(
        &mut self,
        dynamic_amm_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.dynamic_amm_program = Some(dynamic_amm_program);
        self
    }

    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: &'b solana_account_info::AccountInfo<'a>,
        is_writable: bool,
        is_signer: bool,
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .push((account, is_writable, is_signer));
        self
    }

    /// Add additional accounts to the instruction.
    ///
    /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
    /// and a `bool` indicating whether the account is a signer or not.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .extend_from_slice(accounts);
        self
    }

    #[inline(always)]
    pub fn invoke(&self) -> solana_program_entrypoint::ProgramResult {
        self.invoke_signed(&[])
    }

    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed(
        &self,
        signers_seeds: &[&[&[u8]]],
    ) -> solana_program_entrypoint::ProgramResult {
        let instruction = ClaimFeesCpi {
            __program: self.instruction.__program,

            payer: self.instruction.payer.expect("payer is not set"),

            vpool: self.instruction.vpool.expect("vpool is not set"),

            virtuals_mint: self
                .instruction
                .virtuals_mint
                .expect("virtuals_mint is not set"),

            token_mint: self.instruction.token_mint.expect("token_mint is not set"),

            vpool_virtuals_ata: self
                .instruction
                .vpool_virtuals_ata
                .expect("vpool_virtuals_ata is not set"),

            vpool_token_ata: self
                .instruction
                .vpool_token_ata
                .expect("vpool_token_ata is not set"),

            platform: self.instruction.platform.expect("platform is not set"),

            platform_virtuals_ata: self
                .instruction
                .platform_virtuals_ata
                .expect("platform_virtuals_ata is not set"),

            platform_token_ata: self
                .instruction
                .platform_token_ata
                .expect("platform_token_ata is not set"),

            creator_virtuals_ata: self
                .instruction
                .creator_virtuals_ata
                .expect("creator_virtuals_ata is not set"),

            creator_token_ata: self
                .instruction
                .creator_token_ata
                .expect("creator_token_ata is not set"),

            pool: self.instruction.pool.expect("pool is not set"),

            lp_mint: self.instruction.lp_mint.expect("lp_mint is not set"),

            lock_escrow: self
                .instruction
                .lock_escrow
                .expect("lock_escrow is not set"),

            escrow_vault: self
                .instruction
                .escrow_vault
                .expect("escrow_vault is not set"),

            token_program: self
                .instruction
                .token_program
                .expect("token_program is not set"),

            virtuals_vault: self
                .instruction
                .virtuals_vault
                .expect("virtuals_vault is not set"),

            token_vault: self
                .instruction
                .token_vault
                .expect("token_vault is not set"),

            virtuals_token_vault: self
                .instruction
                .virtuals_token_vault
                .expect("virtuals_token_vault is not set"),

            token_token_vault: self
                .instruction
                .token_token_vault
                .expect("token_token_vault is not set"),

            virtuals_vault_lp_mint: self
                .instruction
                .virtuals_vault_lp_mint
                .expect("virtuals_vault_lp_mint is not set"),

            token_vault_lp_mint: self
                .instruction
                .token_vault_lp_mint
                .expect("token_vault_lp_mint is not set"),

            virtuals_vault_lp: self
                .instruction
                .virtuals_vault_lp
                .expect("virtuals_vault_lp is not set"),

            token_vault_lp: self
                .instruction
                .token_vault_lp
                .expect("token_vault_lp is not set"),

            vault_program: self
                .instruction
                .vault_program
                .expect("vault_program is not set"),

            associated_token_program: self
                .instruction
                .associated_token_program
                .expect("associated_token_program is not set"),

            system_program: self
                .instruction
                .system_program
                .expect("system_program is not set"),

            dynamic_amm_program: self
                .instruction
                .dynamic_amm_program
                .expect("dynamic_amm_program is not set"),
        };
        instruction.invoke_signed_with_remaining_accounts(
            signers_seeds,
            &self.instruction.__remaining_accounts,
        )
    }
}

#[derive(Clone, Debug)]
struct ClaimFeesCpiBuilderInstruction<'a, 'b> {
    __program: &'b solana_account_info::AccountInfo<'a>,
    payer: Option<&'b solana_account_info::AccountInfo<'a>>,
    vpool: Option<&'b solana_account_info::AccountInfo<'a>>,
    virtuals_mint: Option<&'b solana_account_info::AccountInfo<'a>>,
    token_mint: Option<&'b solana_account_info::AccountInfo<'a>>,
    vpool_virtuals_ata: Option<&'b solana_account_info::AccountInfo<'a>>,
    vpool_token_ata: Option<&'b solana_account_info::AccountInfo<'a>>,
    platform: Option<&'b solana_account_info::AccountInfo<'a>>,
    platform_virtuals_ata: Option<&'b solana_account_info::AccountInfo<'a>>,
    platform_token_ata: Option<&'b solana_account_info::AccountInfo<'a>>,
    creator_virtuals_ata: Option<&'b solana_account_info::AccountInfo<'a>>,
    creator_token_ata: Option<&'b solana_account_info::AccountInfo<'a>>,
    pool: Option<&'b solana_account_info::AccountInfo<'a>>,
    lp_mint: Option<&'b solana_account_info::AccountInfo<'a>>,
    lock_escrow: Option<&'b solana_account_info::AccountInfo<'a>>,
    escrow_vault: Option<&'b solana_account_info::AccountInfo<'a>>,
    token_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    virtuals_vault: Option<&'b solana_account_info::AccountInfo<'a>>,
    token_vault: Option<&'b solana_account_info::AccountInfo<'a>>,
    virtuals_token_vault: Option<&'b solana_account_info::AccountInfo<'a>>,
    token_token_vault: Option<&'b solana_account_info::AccountInfo<'a>>,
    virtuals_vault_lp_mint: Option<&'b solana_account_info::AccountInfo<'a>>,
    token_vault_lp_mint: Option<&'b solana_account_info::AccountInfo<'a>>,
    virtuals_vault_lp: Option<&'b solana_account_info::AccountInfo<'a>>,
    token_vault_lp: Option<&'b solana_account_info::AccountInfo<'a>>,
    vault_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    associated_token_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    system_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    dynamic_amm_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
    __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}
