[package]
name = "shipstern-core"
description = "Core types for Shipstern"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
readme = "./../../README.md"

[dependencies]
bs58.workspace = true
thiserror.workspace = true
yellowstone-grpc-proto = { workspace = true }
shipstern-proto = { workspace = true, optional = true }
borsh = { workspace = true }
serde = { workspace = true, features = ["derive"] }
clap = { workspace = true, features = ["derive", "cargo", "wrap_help"] }
prost = { workspace = true, optional = true }
prost-types = { workspace = true, optional = true }

[features]
proto = ["dep:shipstern-proto", "dep:prost", "dep:prost-types"]
