//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshDeserialize;
use borsh::BorshSerialize;

pub const CREATE_LOCKER_DISCRIMINATOR: [u8; 8] = [167, 90, 137, 154, 75, 47, 17, 84];

/// Accounts.
#[derive(Debug)]
pub struct CreateLocker {
    /// Virtual pool
    pub virtual_pool: solana_pubkey::Pubkey,
    /// Config
    pub config: solana_pubkey::Pubkey,

    pub pool_authority: solana_pubkey::Pubkey,

    pub base_vault: solana_pubkey::Pubkey,

    pub base_mint: solana_pubkey::Pubkey,

    pub base: solana_pubkey::Pubkey,

    pub creator: solana_pubkey::Pubkey,

    pub escrow: solana_pubkey::Pubkey,

    pub escrow_token: solana_pubkey::Pubkey,

    pub payer: solana_pubkey::Pubkey,

    pub token_program: solana_pubkey::Pubkey,

    pub locker_program: solana_pubkey::Pubkey,

    pub locker_event_authority: solana_pubkey::Pubkey,
    /// System program.
    pub system_program: solana_pubkey::Pubkey,
}

impl CreateLocker {
    pub fn instruction(&self) -> solana_instruction::Instruction {
        self.instruction_with_remaining_accounts(&[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::vec_init_then_push)]
    pub fn instruction_with_remaining_accounts(
        &self,
        remaining_accounts: &[solana_instruction::AccountMeta],
    ) -> solana_instruction::Instruction {
        let mut accounts = Vec::with_capacity(14 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new(
            self.virtual_pool,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.config,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            self.pool_authority,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(self.base_vault, false));
        accounts.push(solana_instruction::AccountMeta::new(self.base_mint, false));
        accounts.push(solana_instruction::AccountMeta::new(self.base, false));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.creator,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(self.escrow, false));
        accounts.push(solana_instruction::AccountMeta::new(
            self.escrow_token,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(self.payer, true));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.token_program,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.locker_program,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.locker_event_authority,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            self.system_program,
            false,
        ));
        accounts.extend_from_slice(remaining_accounts);
        let data = borsh::to_vec(&CreateLockerInstructionData::new()).unwrap();

        solana_instruction::Instruction {
            program_id: crate::DYNAMIC_BONDING_CURVE_ID,
            accounts,
            data,
        }
    }
}

#[derive(BorshSerialize, BorshDeserialize, Clone, Debug, Eq, PartialEq)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct CreateLockerInstructionData {
    discriminator: [u8; 8],
}

impl CreateLockerInstructionData {
    pub fn new() -> Self {
        Self {
            discriminator: [167, 90, 137, 154, 75, 47, 17, 84],
        }
    }
}

impl Default for CreateLockerInstructionData {
    fn default() -> Self {
        Self::new()
    }
}

/// Instruction builder for `CreateLocker`.
///
/// ### Accounts:
///
///   0. `[writable]` virtual_pool
///   1. `[]` config
///   2. `[writable, optional]` pool_authority (default to `FhVo3mqL8PW5pH5U2CN4XE33DokiyZnUwuGpH2hmHLuM`)
///   3. `[writable]` base_vault
///   4. `[writable]` base_mint
///   5. `[writable]` base
///   6. `[]` creator
///   7. `[writable]` escrow
///   8. `[writable]` escrow_token
///   9. `[writable, signer]` payer
///   10. `[optional]` token_program (default to `TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA`)
///   11. `[optional]` locker_program (default to `LocpQgucEQHbqNABEYvBvwoxCPsSbG91A1QaQhQQqjn`)
///   12. `[]` locker_event_authority
///   13. `[optional]` system_program (default to `11111111111111111111111111111111`)
#[derive(Clone, Debug, Default)]
pub struct CreateLockerBuilder {
    virtual_pool: Option<solana_pubkey::Pubkey>,
    config: Option<solana_pubkey::Pubkey>,
    pool_authority: Option<solana_pubkey::Pubkey>,
    base_vault: Option<solana_pubkey::Pubkey>,
    base_mint: Option<solana_pubkey::Pubkey>,
    base: Option<solana_pubkey::Pubkey>,
    creator: Option<solana_pubkey::Pubkey>,
    escrow: Option<solana_pubkey::Pubkey>,
    escrow_token: Option<solana_pubkey::Pubkey>,
    payer: Option<solana_pubkey::Pubkey>,
    token_program: Option<solana_pubkey::Pubkey>,
    locker_program: Option<solana_pubkey::Pubkey>,
    locker_event_authority: Option<solana_pubkey::Pubkey>,
    system_program: Option<solana_pubkey::Pubkey>,
    __remaining_accounts: Vec<solana_instruction::AccountMeta>,
}

impl CreateLockerBuilder {
    pub fn new() -> Self {
        Self::default()
    }
    /// Virtual pool
    #[inline(always)]
    pub fn virtual_pool(&mut self, virtual_pool: solana_pubkey::Pubkey) -> &mut Self {
        self.virtual_pool = Some(virtual_pool);
        self
    }
    /// Config
    #[inline(always)]
    pub fn config(&mut self, config: solana_pubkey::Pubkey) -> &mut Self {
        self.config = Some(config);
        self
    }
    /// `[optional account, default to 'FhVo3mqL8PW5pH5U2CN4XE33DokiyZnUwuGpH2hmHLuM']`
    #[inline(always)]
    pub fn pool_authority(&mut self, pool_authority: solana_pubkey::Pubkey) -> &mut Self {
        self.pool_authority = Some(pool_authority);
        self
    }
    #[inline(always)]
    pub fn base_vault(&mut self, base_vault: solana_pubkey::Pubkey) -> &mut Self {
        self.base_vault = Some(base_vault);
        self
    }
    #[inline(always)]
    pub fn base_mint(&mut self, base_mint: solana_pubkey::Pubkey) -> &mut Self {
        self.base_mint = Some(base_mint);
        self
    }
    #[inline(always)]
    pub fn base(&mut self, base: solana_pubkey::Pubkey) -> &mut Self {
        self.base = Some(base);
        self
    }
    #[inline(always)]
    pub fn creator(&mut self, creator: solana_pubkey::Pubkey) -> &mut Self {
        self.creator = Some(creator);
        self
    }
    #[inline(always)]
    pub fn escrow(&mut self, escrow: solana_pubkey::Pubkey) -> &mut Self {
        self.escrow = Some(escrow);
        self
    }
    #[inline(always)]
    pub fn escrow_token(&mut self, escrow_token: solana_pubkey::Pubkey) -> &mut Self {
        self.escrow_token = Some(escrow_token);
        self
    }
    #[inline(always)]
    pub fn payer(&mut self, payer: solana_pubkey::Pubkey) -> &mut Self {
        self.payer = Some(payer);
        self
    }
    /// `[optional account, default to 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA']`
    #[inline(always)]
    pub fn token_program(&mut self, token_program: solana_pubkey::Pubkey) -> &mut Self {
        self.token_program = Some(token_program);
        self
    }
    /// `[optional account, default to 'LocpQgucEQHbqNABEYvBvwoxCPsSbG91A1QaQhQQqjn']`
    #[inline(always)]
    pub fn locker_program(&mut self, locker_program: solana_pubkey::Pubkey) -> &mut Self {
        self.locker_program = Some(locker_program);
        self
    }
    #[inline(always)]
    pub fn locker_event_authority(
        &mut self,
        locker_event_authority: solana_pubkey::Pubkey,
    ) -> &mut Self {
        self.locker_event_authority = Some(locker_event_authority);
        self
    }
    /// `[optional account, default to '11111111111111111111111111111111']`
    /// System program.
    #[inline(always)]
    pub fn system_program(&mut self, system_program: solana_pubkey::Pubkey) -> &mut Self {
        self.system_program = Some(system_program);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(&mut self, account: solana_instruction::AccountMeta) -> &mut Self {
        self.__remaining_accounts.push(account);
        self
    }
    /// Add additional accounts to the instruction.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[solana_instruction::AccountMeta],
    ) -> &mut Self {
        self.__remaining_accounts.extend_from_slice(accounts);
        self
    }
    #[allow(clippy::clone_on_copy)]
    pub fn instruction(&self) -> solana_instruction::Instruction {
        let accounts = CreateLocker {
            virtual_pool: self.virtual_pool.expect("virtual_pool is not set"),
            config: self.config.expect("config is not set"),
            pool_authority: self.pool_authority.unwrap_or(solana_pubkey::pubkey!(
                "FhVo3mqL8PW5pH5U2CN4XE33DokiyZnUwuGpH2hmHLuM"
            )),
            base_vault: self.base_vault.expect("base_vault is not set"),
            base_mint: self.base_mint.expect("base_mint is not set"),
            base: self.base.expect("base is not set"),
            creator: self.creator.expect("creator is not set"),
            escrow: self.escrow.expect("escrow is not set"),
            escrow_token: self.escrow_token.expect("escrow_token is not set"),
            payer: self.payer.expect("payer is not set"),
            token_program: self.token_program.unwrap_or(solana_pubkey::pubkey!(
                "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
            )),
            locker_program: self.locker_program.unwrap_or(solana_pubkey::pubkey!(
                "LocpQgucEQHbqNABEYvBvwoxCPsSbG91A1QaQhQQqjn"
            )),
            locker_event_authority: self
                .locker_event_authority
                .expect("locker_event_authority is not set"),
            system_program: self
                .system_program
                .unwrap_or(solana_pubkey::pubkey!("11111111111111111111111111111111")),
        };

        accounts.instruction_with_remaining_accounts(&self.__remaining_accounts)
    }
}

/// `create_locker` CPI accounts.
pub struct CreateLockerCpiAccounts<'a, 'b> {
    /// Virtual pool
    pub virtual_pool: &'b solana_account_info::AccountInfo<'a>,
    /// Config
    pub config: &'b solana_account_info::AccountInfo<'a>,

    pub pool_authority: &'b solana_account_info::AccountInfo<'a>,

    pub base_vault: &'b solana_account_info::AccountInfo<'a>,

    pub base_mint: &'b solana_account_info::AccountInfo<'a>,

    pub base: &'b solana_account_info::AccountInfo<'a>,

    pub creator: &'b solana_account_info::AccountInfo<'a>,

    pub escrow: &'b solana_account_info::AccountInfo<'a>,

    pub escrow_token: &'b solana_account_info::AccountInfo<'a>,

    pub payer: &'b solana_account_info::AccountInfo<'a>,

    pub token_program: &'b solana_account_info::AccountInfo<'a>,

    pub locker_program: &'b solana_account_info::AccountInfo<'a>,

    pub locker_event_authority: &'b solana_account_info::AccountInfo<'a>,
    /// System program.
    pub system_program: &'b solana_account_info::AccountInfo<'a>,
}

/// `create_locker` CPI instruction.
pub struct CreateLockerCpi<'a, 'b> {
    /// The program to invoke.
    pub __program: &'b solana_account_info::AccountInfo<'a>,
    /// Virtual pool
    pub virtual_pool: &'b solana_account_info::AccountInfo<'a>,
    /// Config
    pub config: &'b solana_account_info::AccountInfo<'a>,

    pub pool_authority: &'b solana_account_info::AccountInfo<'a>,

    pub base_vault: &'b solana_account_info::AccountInfo<'a>,

    pub base_mint: &'b solana_account_info::AccountInfo<'a>,

    pub base: &'b solana_account_info::AccountInfo<'a>,

    pub creator: &'b solana_account_info::AccountInfo<'a>,

    pub escrow: &'b solana_account_info::AccountInfo<'a>,

    pub escrow_token: &'b solana_account_info::AccountInfo<'a>,

    pub payer: &'b solana_account_info::AccountInfo<'a>,

    pub token_program: &'b solana_account_info::AccountInfo<'a>,

    pub locker_program: &'b solana_account_info::AccountInfo<'a>,

    pub locker_event_authority: &'b solana_account_info::AccountInfo<'a>,
    /// System program.
    pub system_program: &'b solana_account_info::AccountInfo<'a>,
}

impl<'a, 'b> CreateLockerCpi<'a, 'b> {
    pub fn new(
        program: &'b solana_account_info::AccountInfo<'a>,
        accounts: CreateLockerCpiAccounts<'a, 'b>,
    ) -> Self {
        Self {
            __program: program,
            virtual_pool: accounts.virtual_pool,
            config: accounts.config,
            pool_authority: accounts.pool_authority,
            base_vault: accounts.base_vault,
            base_mint: accounts.base_mint,
            base: accounts.base,
            creator: accounts.creator,
            escrow: accounts.escrow,
            escrow_token: accounts.escrow_token,
            payer: accounts.payer,
            token_program: accounts.token_program,
            locker_program: accounts.locker_program,
            locker_event_authority: accounts.locker_event_authority,
            system_program: accounts.system_program,
        }
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], &[])
    }
    #[inline(always)]
    pub fn invoke_with_remaining_accounts(
        &self,
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(&[], remaining_accounts)
    }
    #[inline(always)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        self.invoke_signed_with_remaining_accounts(signers_seeds, &[])
    }
    #[allow(clippy::arithmetic_side_effects)]
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed_with_remaining_accounts(
        &self,
        signers_seeds: &[&[&[u8]]],
        remaining_accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> solana_program_error::ProgramResult {
        let mut accounts = Vec::with_capacity(14 + remaining_accounts.len());
        accounts.push(solana_instruction::AccountMeta::new(
            *self.virtual_pool.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.config.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.pool_authority.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.base_vault.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.base_mint.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(*self.base.key, false));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.creator.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.escrow.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(
            *self.escrow_token.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new(*self.payer.key, true));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.token_program.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.locker_program.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.locker_event_authority.key,
            false,
        ));
        accounts.push(solana_instruction::AccountMeta::new_readonly(
            *self.system_program.key,
            false,
        ));
        remaining_accounts.iter().for_each(|remaining_account| {
            accounts.push(solana_instruction::AccountMeta {
                pubkey: *remaining_account.0.key,
                is_signer: remaining_account.1,
                is_writable: remaining_account.2,
            })
        });
        let data = borsh::to_vec(&CreateLockerInstructionData::new()).unwrap();

        let instruction = solana_instruction::Instruction {
            program_id: crate::DYNAMIC_BONDING_CURVE_ID,
            accounts,
            data,
        };
        let mut account_infos = Vec::with_capacity(15 + remaining_accounts.len());
        account_infos.push(self.__program.clone());
        account_infos.push(self.virtual_pool.clone());
        account_infos.push(self.config.clone());
        account_infos.push(self.pool_authority.clone());
        account_infos.push(self.base_vault.clone());
        account_infos.push(self.base_mint.clone());
        account_infos.push(self.base.clone());
        account_infos.push(self.creator.clone());
        account_infos.push(self.escrow.clone());
        account_infos.push(self.escrow_token.clone());
        account_infos.push(self.payer.clone());
        account_infos.push(self.token_program.clone());
        account_infos.push(self.locker_program.clone());
        account_infos.push(self.locker_event_authority.clone());
        account_infos.push(self.system_program.clone());
        remaining_accounts
            .iter()
            .for_each(|remaining_account| account_infos.push(remaining_account.0.clone()));

        if signers_seeds.is_empty() {
            solana_cpi::invoke(&instruction, &account_infos)
        } else {
            solana_cpi::invoke_signed(&instruction, &account_infos, signers_seeds)
        }
    }
}

/// Instruction builder for `CreateLocker` via CPI.
///
/// ### Accounts:
///
///   0. `[writable]` virtual_pool
///   1. `[]` config
///   2. `[writable]` pool_authority
///   3. `[writable]` base_vault
///   4. `[writable]` base_mint
///   5. `[writable]` base
///   6. `[]` creator
///   7. `[writable]` escrow
///   8. `[writable]` escrow_token
///   9. `[writable, signer]` payer
///   10. `[]` token_program
///   11. `[]` locker_program
///   12. `[]` locker_event_authority
///   13. `[]` system_program
#[derive(Clone, Debug)]
pub struct CreateLockerCpiBuilder<'a, 'b> {
    instruction: Box<CreateLockerCpiBuilderInstruction<'a, 'b>>,
}

impl<'a, 'b> CreateLockerCpiBuilder<'a, 'b> {
    pub fn new(program: &'b solana_account_info::AccountInfo<'a>) -> Self {
        let instruction = Box::new(CreateLockerCpiBuilderInstruction {
            __program: program,
            virtual_pool: None,
            config: None,
            pool_authority: None,
            base_vault: None,
            base_mint: None,
            base: None,
            creator: None,
            escrow: None,
            escrow_token: None,
            payer: None,
            token_program: None,
            locker_program: None,
            locker_event_authority: None,
            system_program: None,
            __remaining_accounts: Vec::new(),
        });
        Self { instruction }
    }
    /// Virtual pool
    #[inline(always)]
    pub fn virtual_pool(
        &mut self,
        virtual_pool: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.virtual_pool = Some(virtual_pool);
        self
    }
    /// Config
    #[inline(always)]
    pub fn config(&mut self, config: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.config = Some(config);
        self
    }
    #[inline(always)]
    pub fn pool_authority(
        &mut self,
        pool_authority: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.pool_authority = Some(pool_authority);
        self
    }
    #[inline(always)]
    pub fn base_vault(
        &mut self,
        base_vault: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.base_vault = Some(base_vault);
        self
    }
    #[inline(always)]
    pub fn base_mint(&mut self, base_mint: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.base_mint = Some(base_mint);
        self
    }
    #[inline(always)]
    pub fn base(&mut self, base: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.base = Some(base);
        self
    }
    #[inline(always)]
    pub fn creator(&mut self, creator: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.creator = Some(creator);
        self
    }
    #[inline(always)]
    pub fn escrow(&mut self, escrow: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.escrow = Some(escrow);
        self
    }
    #[inline(always)]
    pub fn escrow_token(
        &mut self,
        escrow_token: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.escrow_token = Some(escrow_token);
        self
    }
    #[inline(always)]
    pub fn payer(&mut self, payer: &'b solana_account_info::AccountInfo<'a>) -> &mut Self {
        self.instruction.payer = Some(payer);
        self
    }
    #[inline(always)]
    pub fn token_program(
        &mut self,
        token_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.token_program = Some(token_program);
        self
    }
    #[inline(always)]
    pub fn locker_program(
        &mut self,
        locker_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.locker_program = Some(locker_program);
        self
    }
    #[inline(always)]
    pub fn locker_event_authority(
        &mut self,
        locker_event_authority: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.locker_event_authority = Some(locker_event_authority);
        self
    }
    /// System program.
    #[inline(always)]
    pub fn system_program(
        &mut self,
        system_program: &'b solana_account_info::AccountInfo<'a>,
    ) -> &mut Self {
        self.instruction.system_program = Some(system_program);
        self
    }
    /// Add an additional account to the instruction.
    #[inline(always)]
    pub fn add_remaining_account(
        &mut self,
        account: &'b solana_account_info::AccountInfo<'a>,
        is_writable: bool,
        is_signer: bool,
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .push((account, is_writable, is_signer));
        self
    }
    /// Add additional accounts to the instruction.
    ///
    /// Each account is represented by a tuple of the `AccountInfo`, a `bool` indicating whether the account is writable or not,
    /// and a `bool` indicating whether the account is a signer or not.
    #[inline(always)]
    pub fn add_remaining_accounts(
        &mut self,
        accounts: &[(&'b solana_account_info::AccountInfo<'a>, bool, bool)],
    ) -> &mut Self {
        self.instruction
            .__remaining_accounts
            .extend_from_slice(accounts);
        self
    }
    #[inline(always)]
    pub fn invoke(&self) -> solana_program_error::ProgramResult {
        self.invoke_signed(&[])
    }
    #[allow(clippy::clone_on_copy)]
    #[allow(clippy::vec_init_then_push)]
    pub fn invoke_signed(&self, signers_seeds: &[&[&[u8]]]) -> solana_program_error::ProgramResult {
        let instruction = CreateLockerCpi {
            __program: self.instruction.__program,

            virtual_pool: self
                .instruction
                .virtual_pool
                .expect("virtual_pool is not set"),

            config: self.instruction.config.expect("config is not set"),

            pool_authority: self
                .instruction
                .pool_authority
                .expect("pool_authority is not set"),

            base_vault: self.instruction.base_vault.expect("base_vault is not set"),

            base_mint: self.instruction.base_mint.expect("base_mint is not set"),

            base: self.instruction.base.expect("base is not set"),

            creator: self.instruction.creator.expect("creator is not set"),

            escrow: self.instruction.escrow.expect("escrow is not set"),

            escrow_token: self
                .instruction
                .escrow_token
                .expect("escrow_token is not set"),

            payer: self.instruction.payer.expect("payer is not set"),

            token_program: self
                .instruction
                .token_program
                .expect("token_program is not set"),

            locker_program: self
                .instruction
                .locker_program
                .expect("locker_program is not set"),

            locker_event_authority: self
                .instruction
                .locker_event_authority
                .expect("locker_event_authority is not set"),

            system_program: self
                .instruction
                .system_program
                .expect("system_program is not set"),
        };
        instruction.invoke_signed_with_remaining_accounts(
            signers_seeds,
            &self.instruction.__remaining_accounts,
        )
    }
}

#[derive(Clone, Debug)]
struct CreateLockerCpiBuilderInstruction<'a, 'b> {
    __program: &'b solana_account_info::AccountInfo<'a>,
    virtual_pool: Option<&'b solana_account_info::AccountInfo<'a>>,
    config: Option<&'b solana_account_info::AccountInfo<'a>>,
    pool_authority: Option<&'b solana_account_info::AccountInfo<'a>>,
    base_vault: Option<&'b solana_account_info::AccountInfo<'a>>,
    base_mint: Option<&'b solana_account_info::AccountInfo<'a>>,
    base: Option<&'b solana_account_info::AccountInfo<'a>>,
    creator: Option<&'b solana_account_info::AccountInfo<'a>>,
    escrow: Option<&'b solana_account_info::AccountInfo<'a>>,
    escrow_token: Option<&'b solana_account_info::AccountInfo<'a>>,
    payer: Option<&'b solana_account_info::AccountInfo<'a>>,
    token_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    locker_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    locker_event_authority: Option<&'b solana_account_info::AccountInfo<'a>>,
    system_program: Option<&'b solana_account_info::AccountInfo<'a>>,
    /// Additional instruction accounts `(AccountInfo, is_writable, is_signer)`.
    __remaining_accounts: Vec<(&'b solana_account_info::AccountInfo<'a>, bool, bool)>,
}
