[package]
name = "shipstern-spl-token-extensions-parser"
description = "Shipstern program parsers for spl token exetensions parser."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
readme = "./../../README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = { workspace = true, optional = true }
prost-types = { workspace = true, optional = true }
spl-pod = { workspace = true }
spl-token-2022 = { workspace = true, features = ["no-entrypoint"] }
spl-type-length-value = { workspace = true }
spl-token-group-interface = { workspace = true }
spl-token-metadata-interface = { workspace = true }
solana-program-pack = { workspace = true }
solana-program-error = { workspace = true }
shipstern-core = { workspace = true }
shipstern-proc-macro = { workspace = true }
shipstern-parser = { workspace = true }
shipstern-spl-token-parser = { workspace = true }
shipstern-proto = { workspace = true, features = [
  "parser",
], optional = true }
thiserror.workspace = true
bs58.workspace = true
bytemuck = { workspace = true }
borsh = { workspace = true }

[dev-dependencies]
shipstern-mock = { workspace = true }
tokio.workspace = true
solana-pubkey = { workspace = true }

[features]
default = []
proto = [
  "dep:prost",
  "dep:prost-types",
  "dep:shipstern-proto",
  "shipstern-core/proto",
  "shipstern-proc-macro/proto",
  "shipstern-proto/parser",
  "shipstern-parser/proto",
  "shipstern-spl-token-parser/proto",
]
