[package]
name = "shipstern-spl-token-parser"
description = "Shipstern program parsers for spl token program."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
readme = "./../../README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = { workspace = true, optional = true }
prost-types = { workspace = true, optional = true }
spl-pod = { workspace = true }
spl-token = { workspace = true }
solana-program-error = { workspace = true }
shipstern-core = { workspace = true }
shipstern-parser = { workspace = true }
shipstern-proc-macro = { workspace = true }
shipstern-proto = { workspace = true, features = [
  "parser",
], optional = true }
thiserror.workspace = true
bs58.workspace = true
tracing = { workspace = true, optional = true }
strum = { workspace = true, optional = true }
strum_macros = { workspace = true, optional = true }
bytemuck = { workspace = true, optional = true }

[dev-dependencies]
shipstern-mock = { workspace = true }
tokio.workspace = true

[features]
default = []
proto = [
  "dep:prost",
  "dep:prost-types",
  "dep:shipstern-proto",
  "shipstern-core/proto",
  "shipstern-proc-macro/proto",
  "shipstern-proto/parser",
  "shipstern-parser/proto",
]
